export const serviceCatalog = [
  {
    slug: "creation-site-web-maroc",
    icon: "Code",
    related: ["ui-ux-identite-visuelle", "landing-page-maroc", "seo-maroc"],
    fr: {
      name: "Sites web premium",
      metaTitle: "Création de site web au Maroc",
      metaDescription: "Création de sites web rapides et sur mesure à Casablanca : design premium, SEO technique et parcours pensé pour transformer vos visiteurs en prospects.",
      eyebrow: "Création de sites web · Casablanca & Maroc",
      title: "Création de site web premium au Maroc",
      highlight: "Une présence digitale qui inspire confiance et génère des contacts.",
      description: "Nous concevons des sites vitrines rapides, élégants et faciles à faire évoluer pour les entreprises marocaines qui veulent présenter clairement leur valeur et convertir davantage de visiteurs.",
      introTitle: "Votre site doit travailler pour votre activité",
      intro: [
        "Un beau site ne suffit pas. Il doit expliquer votre offre en quelques secondes, rassurer le visiteur et lui donner une prochaine action évidente. Nous réunissons stratégie, contenu, design UI/UX et développement pour construire ce parcours sans friction.",
        "Chaque page est pensée pour le mobile, la vitesse et le référencement naturel. L’architecture reste claire pour Google comme pour vos prospects, tandis que le design traduit la personnalité de votre marque sans sacrifier la lisibilité.",
      ],
      benefits: [
        { title: "Crédibilité immédiate", text: "Une direction visuelle cohérente et un message précis pour donner confiance dès la première visite." },
        { title: "Performance durable", text: "Une base Next.js rapide, responsive et structurée pour les Core Web Vitals et le SEO technique." },
        { title: "Conversion claire", text: "Des appels à l’action, preuves et formulaires placés selon le parcours réel de vos futurs clients." },
      ],
      deliverables: ["Architecture des pages", "Design responsive", "Développement Next.js", "SEO technique", "Connexion WhatsApp", "Mesure des conversions"],
      process: [
        { title: "Cadrage", text: "Objectifs, audience, concurrence, contenus disponibles et action principale attendue." },
        { title: "UX & direction visuelle", text: "Structure des pages, hiérarchie du message et interface alignée avec votre identité." },
        { title: "Développement", text: "Intégration responsive, animations utiles, optimisation des images et des performances." },
        { title: "Mise en ligne", text: "Contrôles techniques, indexation, analytics et prise en main de votre nouveau site." },
      ],
      audiences: ["PME et entreprises de services", "Cabinets et professions libérales", "Marques premium", "Projets en lancement ou en refonte"],
      faq: [
        { q: "Combien coûte un site web professionnel au Maroc ?", a: "Le budget dépend du nombre de pages, du contenu, des fonctionnalités et du niveau de design. Après un échange court, nous définissons un périmètre précis et un devis adapté à votre priorité commerciale." },
        { q: "Le site sera-t-il optimisé pour Google ?", a: "Oui. La structure sémantique, les métadonnées, la vitesse, le mobile, le sitemap et les données structurées font partie de la base. Le positionnement dépend ensuite aussi du contenu, de la concurrence et de l’autorité du domaine." },
        { q: "Pourrai-je modifier le contenu ?", a: "Le mode d’édition est choisi selon votre besoin : contenu intégré, CMS ou interface d’administration. Nous privilégions la solution la plus simple à maintenir pour votre équipe." },
        { q: "Pouvez-vous refaire un site existant ?", a: "Oui. Nous auditons les pages et URLs existantes, conservons ce qui apporte de la valeur puis améliorons l’expérience, la vitesse et le parcours de conversion." },
      ],
    },
    ar: {
      name: "تصميم وتطوير المواقع",
      metaTitle: "تصميم مواقع احترافية في المغرب",
      metaDescription: "تصميم مواقع سريعة ومخصصة في الدار البيضاء والمغرب، بهوية احترافية وSEO تقني ومسار واضح لتحويل الزوار إلى عملاء محتملين.",
      eyebrow: "تصميم المواقع · الدار البيضاء والمغرب",
      title: "تصميم موقع احترافي في المغرب",
      highlight: "حضور رقمي يعكس قيمة مشروعك ويحول الزيارات إلى تواصل حقيقي.",
      description: "نصمم مواقع شركات سريعة وأنيقة وقابلة للتطوير، تساعد المشروع المغربي على توضيح خدماته، بناء الثقة وتسهيل انتقال الزائر إلى طلب عرض أو تواصل مباشر.",
      introTitle: "موقعك يجب أن يخدم أهداف نشاطك",
      intro: [
        "الموقع الجميل وحده لا يكفي. يجب أن يشرح عرضك بسرعة، يطمئن الزائر ويقوده إلى خطوة واضحة. لذلك نجمع بين الاستراتيجية والمحتوى وتجربة المستخدم والتطوير لبناء مسار بسيط ومقنع.",
        "نخطط كل صفحة للهاتف والسرعة والظهور في محركات البحث. تكون البنية واضحة لجوجل وللعميل، بينما يعبر التصميم عن شخصية العلامة من دون التضحية بسهولة القراءة.",
      ],
      benefits: [
        { title: "مصداقية من أول زيارة", text: "هوية بصرية متناسقة ورسالة واضحة تعطي العميل سبباً للثقة في مشروعك." },
        { title: "أداء مستدام", text: "بنية Next.js سريعة ومتجاوبة ومهيأة للـSEO التقني ومؤشرات الأداء الأساسية." },
        { title: "تحويل واضح", text: "دعوات للتواصل ونقاط ثقة ونماذج موضوعة حسب رحلة العميل الفعلية." },
      ],
      deliverables: ["هيكلة الصفحات", "تصميم متجاوب", "تطوير Next.js", "SEO تقني", "ربط واتساب", "قياس التحويلات"],
      process: [
        { title: "تحديد المشروع", text: "نفهم الهدف والجمهور والمنافسين والمحتوى والخطوة الأساسية المطلوبة من الزائر." },
        { title: "التجربة والهوية", text: "نبني هيكلة الصفحات وترتيب الرسائل وواجهة متناسقة مع هوية العلامة." },
        { title: "التطوير", text: "تنفيذ متجاوب، حركات مفيدة، تحسين الصور وسرعة التصفح." },
        { title: "الإطلاق", text: "مراجعة تقنية، إعداد الفهرسة والتحليلات وتسليم طريقة إدارة الموقع." },
      ],
      audiences: ["الشركات الصغيرة والمتوسطة", "المكاتب والخدمات المهنية", "العلامات الراقية", "المشاريع الجديدة أو التي تحتاج إعادة تصميم"],
      faq: [
        { q: "كم تبلغ تكلفة تصميم موقع احترافي في المغرب؟", a: "تختلف الميزانية حسب عدد الصفحات والمحتوى والوظائف ومستوى التصميم. بعد محادثة قصيرة نحدد نطاقاً واضحاً ونقدم عرضاً مناسباً لأولويات المشروع." },
        { q: "هل سيكون الموقع مهيأً للظهور في Google؟", a: "نعم. البنية الدلالية والبيانات الوصفية والسرعة والهاتف وخريطة الموقع والبيانات المنظمة تدخل ضمن الأساس. أما الترتيب فيعتمد أيضاً على جودة المحتوى والمنافسة وقوة النطاق." },
        { q: "هل يمكنني تعديل المحتوى لاحقاً؟", a: "نختار طريقة التحرير حسب حاجتك: محتوى مدمج أو CMS أو لوحة إدارة. الهدف هو أن تكون الصيانة بسيطة ومناسبة لفريقك." },
        { q: "هل يمكنكم إعادة تصميم موقع موجود؟", a: "نعم. نراجع الصفحات والروابط الحالية، نحافظ على العناصر المفيدة ثم نحسن التجربة والسرعة ومسار التحويل." },
      ],
    },
  },
  {
    slug: "ui-ux-identite-visuelle",
    icon: "Palette",
    related: ["creation-site-web-maroc", "landing-page-maroc", "application-web-sur-mesure"],
    fr: {
      name: "UI/UX & identité",
      metaTitle: "Design UI/UX & identité digitale au Maroc",
      metaDescription: "Design UI/UX et identité digitale à Casablanca : interfaces claires, design system cohérent et expérience pensée pour renforcer votre marque.",
      eyebrow: "UI/UX design · Identité digitale",
      title: "Design UI/UX et identité digitale au Maroc",
      highlight: "Une interface reconnaissable, cohérente et simple à utiliser.",
      description: "Nous transformons votre positionnement en un système visuel complet : hiérarchie, couleurs, typographie, composants et interactions qui renforcent la confiance sans compliquer l’expérience.",
      introTitle: "Le design devient un système, pas une décoration",
      intro: [
        "Une bonne interface aide l’utilisateur à comprendre où il se trouve, ce qu’il peut faire et pourquoi il doit continuer. Nous commençons par les usages, les priorités métier et le contenu avant de définir l’esthétique.",
        "Le résultat est un design system réutilisable qui garde votre site, vos landing pages et vos applications cohérents. Votre équipe gagne du temps et votre marque devient plus facile à reconnaître.",
      ],
      benefits: [
        { title: "Parcours plus intuitif", text: "Navigation, hiérarchie et micro-interactions conçues autour des questions réelles de l’utilisateur." },
        { title: "Marque cohérente", text: "Palette, typographies, iconographie et composants réunis dans un langage visuel durable." },
        { title: "Évolution plus rapide", text: "Des règles et composants réutilisables pour créer de nouvelles pages sans repartir de zéro." },
      ],
      deliverables: ["Audit UX", "Wireframes", "Direction artistique", "Design system", "Prototype interactif", "Guide de composants"],
      process: [
        { title: "Recherche", text: "Objectifs, utilisateurs, points de friction, références et contraintes techniques." },
        { title: "Structure", text: "Parcours, wireframes et priorisation du contenu avant toute décision esthétique." },
        { title: "Système visuel", text: "Couleurs, typographies, grilles, composants, états et principes de mouvement." },
        { title: "Prototype & validation", text: "Écrans interactifs, contrôles de cohérence et préparation pour le développement." },
      ],
      audiences: ["Marques en création", "Entreprises en repositionnement", "SaaS et applications métier", "Sites dont l’interface manque de cohérence"],
      faq: [
        { q: "Quelle est la différence entre UI et UX ?", a: "L’UX organise l’expérience, le parcours et la facilité d’usage. L’UI définit l’aspect visuel et les interactions. Les deux doivent avancer ensemble pour produire une interface utile et crédible." },
        { q: "Pouvez-vous travailler avec notre logo actuel ?", a: "Oui. Nous pouvons prolonger une identité existante, la clarifier ou proposer une évolution ciblée sans imposer une refonte complète." },
        { q: "Recevons-nous les fichiers et composants ?", a: "Oui. Les écrans, composants, variantes et règles utiles sont organisés pour faciliter le développement et les futures évolutions." },
        { q: "Le design sera-t-il adapté au mobile ?", a: "Oui. Les parcours et composants sont pensés pour les différentes tailles d’écran, avec une attention particulière au tactile, à la lisibilité et aux actions prioritaires." },
      ],
    },
    ar: {
      name: "هوية وتجربة المستخدم",
      metaTitle: "تصميم UI/UX وهوية رقمية في المغرب",
      metaDescription: "تصميم UI/UX وهوية رقمية في الدار البيضاء: واجهات واضحة، نظام تصميم متناسق وتجربة تعزز ثقة المستخدم في علامتك.",
      eyebrow: "تجربة المستخدم · الهوية الرقمية",
      title: "تصميم UI/UX وهوية رقمية في المغرب",
      highlight: "واجهة مميزة ومتناسقة وسهلة الاستخدام على كل شاشة.",
      description: "نحول تموقع علامتك إلى نظام بصري متكامل: ترتيب المحتوى والألوان والخطوط والمكونات والتفاعلات، لبناء الثقة من دون تعقيد تجربة المستخدم.",
      introTitle: "التصميم نظام متكامل وليس مجرد زينة",
      intro: [
        "الواجهة الجيدة تساعد المستخدم على فهم مكانه وما يمكنه فعله ولماذا يستمر. نبدأ من حاجات المستخدم وأهداف النشاط والمحتوى قبل اختيار الأسلوب البصري.",
        "النتيجة هي Design System قابل لإعادة الاستخدام يحافظ على تناسق الموقع وصفحات الهبوط والتطبيقات، ويوفر الوقت لفريقك ويقوي تميز العلامة.",
      ],
      benefits: [
        { title: "مسار سهل وواضح", text: "تنقل وترتيب وتفاعلات صغيرة مبنية حول الأسئلة الحقيقية للمستخدم." },
        { title: "علامة متناسقة", text: "ألوان وخطوط وأيقونات ومكونات ضمن لغة بصرية موحدة وقابلة للاستمرار." },
        { title: "تطوير أسرع", text: "قواعد ومكونات قابلة لإعادة الاستخدام لبناء صفحات جديدة من دون البداية من الصفر." },
      ],
      deliverables: ["مراجعة UX", "Wireframes", "توجه فني", "Design system", "نموذج تفاعلي", "دليل المكونات"],
      process: [
        { title: "البحث", text: "نفهم الأهداف والمستخدمين ونقاط الصعوبة والمراجع والقيود التقنية." },
        { title: "الهيكلة", text: "نحدد المسار والـwireframes وأولوية المحتوى قبل القرارات الجمالية." },
        { title: "النظام البصري", text: "ألوان وخطوط وشبكات ومكونات وحالات ومبادئ الحركة." },
        { title: "النموذج والمراجعة", text: "شاشات تفاعلية ومراجعة التناسق وتحضير واضح لمرحلة التطوير." },
      ],
      audiences: ["العلامات الجديدة", "الشركات التي تعيد تموقعها", "تطبيقات SaaS والأعمال", "المواقع ذات الواجهة غير المتناسقة"],
      faq: [
        { q: "ما الفرق بين UI وUX؟", a: "UX ينظم التجربة والمسار وسهولة الاستخدام، بينما UI يحدد الشكل البصري والتفاعلات. الجمع بينهما ضروري لبناء واجهة مفيدة وموثوقة." },
        { q: "هل يمكن العمل بالهوية الحالية؟", a: "نعم. يمكننا توسيع الهوية الموجودة أو توضيحها أو اقتراح تطوير مركز من دون فرض تغيير شامل." },
        { q: "هل نحصل على الملفات والمكونات؟", a: "نعم. ننظم الشاشات والمكونات والحالات والقواعد المفيدة لتسهيل التطوير والتحديثات المستقبلية." },
        { q: "هل سيكون التصميم متجاوباً مع الهاتف؟", a: "نعم. نصمم المسارات والمكونات لمختلف الشاشات مع اهتمام خاص باللمس والقراءة والإجراءات الأساسية." },
      ],
    },
  },
  {
    slug: "landing-page-maroc",
    icon: "MousePointer2",
    related: ["ui-ux-identite-visuelle", "creation-site-web-maroc", "seo-maroc"],
    fr: {
      name: "Landing pages",
      metaTitle: "Création de landing page au Maroc",
      metaDescription: "Landing pages rapides et orientées conversion au Maroc pour campagnes Meta Ads et Google Ads, lancement d’offre et génération de prospects.",
      eyebrow: "Landing pages · Acquisition & conversion",
      title: "Création de landing page au Maroc",
      highlight: "Une page concentrée sur une offre, une audience et une action.",
      description: "Nous créons des pages d’atterrissage rapides pour transformer le trafic de vos campagnes en demandes qualifiées, prises de rendez-vous ou conversations WhatsApp.",
      introTitle: "Chaque clic publicitaire doit arriver au bon message",
      intro: [
        "Envoyer une campagne vers une page générique dilue l’intention. Une landing page reprend la promesse de l’annonce, répond aux objections essentielles et maintient l’utilisateur concentré sur une seule prochaine étape.",
        "Nous travaillons le message, la hiérarchie, les preuves et la vitesse ensemble. La mesure des événements permet ensuite de comprendre ce qui génère réellement des contacts et d’améliorer la page avec des données utiles.",
      ],
      benefits: [
        { title: "Message aligné", text: "La promesse de la publicité continue sur la page pour éviter la rupture et la confusion." },
        { title: "Moins de distractions", text: "Une structure courte, des objections traitées et un appel à l’action principal clairement répété." },
        { title: "Mesure exploitable", text: "Événements de conversion et paramètres de campagne préparés pour analyser la qualité des leads." },
      ],
      deliverables: ["Structure de conversion", "Copywriting de page", "Design responsive", "Développement rapide", "Tracking GA4", "CTA formulaire ou WhatsApp"],
      process: [
        { title: "Offre & audience", text: "Nous clarifions la promesse, la source du trafic et l’action qui définit une conversion." },
        { title: "Message", text: "Accroche, bénéfices, preuves, objections et appels à l’action organisés dans le bon ordre." },
        { title: "Design & build", text: "Interface rapide et mobile-first, cohérente avec la campagne et votre marque." },
        { title: "Mesure", text: "Configuration des événements et lecture des premiers signaux pour guider les améliorations." },
      ],
      audiences: ["Campagnes Meta Ads", "Campagnes Google Ads", "Lancement d’une nouvelle offre", "Génération de rendez-vous ou leads"],
      faq: [
        { q: "Pourquoi ne pas utiliser la page d’accueil ?", a: "La page d’accueil présente toute l’entreprise. Une landing page répond à une intention précise et réduit les distractions, ce qui facilite la mesure et l’optimisation de la campagne." },
        { q: "Pouvez-vous rédiger le contenu ?", a: "Oui. Nous structurons le message à partir de votre offre, vos preuves et les questions de vos clients. Votre validation garantit que chaque promesse reste exacte." },
        { q: "La landing page fonctionne-t-elle avec Meta et Google Ads ?", a: "Oui. Elle peut être adaptée aux deux canaux, avec un message et un suivi cohérents selon la campagne et les paramètres utilisés." },
        { q: "Peut-on tester plusieurs versions ?", a: "La structure peut être préparée pour comparer des accroches, preuves ou appels à l’action. Un test utile nécessite toutefois assez de trafic et un objectif de conversion bien défini." },
      ],
    },
    ar: {
      name: "صفحات الهبوط",
      metaTitle: "تصميم Landing Page في المغرب",
      metaDescription: "صفحات هبوط سريعة وموجهة للتحويل في المغرب لحملات Meta Ads وGoogle Ads، إطلاق العروض وجمع العملاء المحتملين.",
      eyebrow: "صفحات الهبوط · الإعلانات والتحويل",
      title: "تصميم Landing Page في المغرب",
      highlight: "صفحة تركز على عرض واحد وجمهور واحد وخطوة واحدة واضحة.",
      description: "نصمم صفحات هبوط سريعة تحول زيارات الحملات الإعلانية إلى طلبات مؤهلة أو حجوزات أو محادثات مباشرة عبر واتساب.",
      introTitle: "كل نقرة إعلانية تحتاج الرسالة المناسبة",
      intro: [
        "إرسال الحملة إلى صفحة عامة يضعف نية المستخدم. صفحة الهبوط تكمل وعد الإعلان، تجيب عن الاعتراضات المهمة وتحافظ على تركيز الزائر على خطوة واحدة.",
        "نعمل على الرسالة والترتيب ونقاط الثقة والسرعة معاً. ثم يساعد قياس الأحداث على معرفة ما يجلب التواصل فعلاً وتحسين الصفحة ببيانات واضحة.",
      ],
      benefits: [
        { title: "رسالة متناسقة", text: "يستمر وعد الإعلان داخل الصفحة من دون انقطاع أو ارتباك." },
        { title: "تشتيت أقل", text: "هيكلة مركزة واعتراضات مجابة ودعوة أساسية تتكرر بوضوح." },
        { title: "قياس مفيد", text: "إعداد أحداث التحويل ومعلمات الحملة لتحليل جودة العملاء المحتملين." },
      ],
      deliverables: ["هيكلة التحويل", "كتابة محتوى الصفحة", "تصميم متجاوب", "تطوير سريع", "تتبع GA4", "نموذج أو CTA واتساب"],
      process: [
        { title: "العرض والجمهور", text: "نوضح الوعد ومصدر الزيارات والخطوة التي تعتبر تحويلاً." },
        { title: "الرسالة", text: "نرتب العنوان والفوائد والأدلة والاعتراضات والدعوات إلى الإجراء." },
        { title: "التصميم والتطوير", text: "واجهة سريعة للهاتف ومتناسقة مع الحملة وهوية العلامة." },
        { title: "القياس", text: "إعداد الأحداث وقراءة المؤشرات الأولى لتوجيه التحسينات." },
      ],
      audiences: ["حملات Meta Ads", "حملات Google Ads", "إطلاق عرض جديد", "جمع المواعيد والعملاء المحتملين"],
      faq: [
        { q: "لماذا لا أستخدم الصفحة الرئيسية؟", a: "الصفحة الرئيسية تقدم الشركة كلها، أما صفحة الهبوط فتجيب عن نية محددة وتقلل التشتيت، لذلك يسهل قياس الحملة وتحسينها." },
        { q: "هل يمكنكم كتابة المحتوى؟", a: "نعم. نبني الرسالة انطلاقاً من العرض والأدلة وأسئلة العملاء، وتضمن مراجعتك أن كل وعد دقيق." },
        { q: "هل تعمل الصفحة مع Meta وGoogle Ads؟", a: "نعم. يمكن تكييفها للقناتين مع رسالة وتتبع متناسقين حسب الحملة والمعلمات المستخدمة." },
        { q: "هل يمكن اختبار أكثر من نسخة؟", a: "يمكن تحضير الهيكلة لمقارنة العناوين أو الأدلة أو الدعوات. الاختبار المفيد يحتاج عدداً مناسباً من الزيارات وهدف تحويل واضحاً." },
      ],
    },
  },
  {
    slug: "ecommerce-maroc",
    icon: "ShoppingCart",
    related: ["creation-site-web-maroc", "backend-api", "maintenance-site-web"],
    fr: {
      name: "E-commerce",
      metaTitle: "Création de site e-commerce au Maroc",
      metaDescription: "Création de boutiques e-commerce rapides au Maroc : catalogue, commande, paiement, livraison et administration adaptés à votre activité.",
      eyebrow: "E-commerce · Vente en ligne au Maroc",
      title: "Création de site e-commerce au Maroc",
      highlight: "Une boutique simple à acheter, simple à gérer et prête à évoluer.",
      description: "Nous construisons des expériences e-commerce adaptées au marché marocain, depuis le catalogue et la fiche produit jusqu’à la commande, au paiement et au suivi opérationnel.",
      introTitle: "La performance commerciale se joue dans tout le parcours",
      intro: [
        "Une boutique en ligne doit réduire les hésitations à chaque étape : trouver le bon produit, comprendre l’offre, vérifier la livraison puis finaliser la commande sans surprise. Nous concevons ce parcours autour de vos produits et de votre organisation réelle.",
        "La solution technique dépend du catalogue, du volume de commandes, des moyens de paiement, de la livraison et des outils internes. Nous évitons la complexité inutile pour proposer une base fiable que votre équipe peut gérer.",
      ],
      benefits: [
        { title: "Achat sans friction", text: "Recherche, catégories, fiches produit, panier et commande hiérarchisés pour le mobile." },
        { title: "Gestion adaptée", text: "Catalogue, stock, commandes et contenus organisés selon le fonctionnement de votre équipe." },
        { title: "Base évolutive", text: "Architecture capable d’intégrer de nouveaux produits, paiements, transporteurs ou automatisations." },
      ],
      deliverables: ["Catalogue et catégories", "Fiches produit", "Panier et commande", "Paiement adapté", "Gestion des commandes", "Analytics e-commerce"],
      process: [
        { title: "Modèle commercial", text: "Produits, variantes, prix, stock, paiement, livraison et règles opérationnelles." },
        { title: "Parcours client", text: "Navigation, recherche, fiche produit, panier et étapes de commande sur mobile." },
        { title: "Intégrations", text: "Connexion des services nécessaires et préparation de l’administration quotidienne." },
        { title: "Tests & lancement", text: "Scénarios de commande, contrôles de performance, mesure et accompagnement de l’équipe." },
      ],
      audiences: ["Marques avec catalogue", "Commerce physique qui passe en ligne", "Projets D2C", "Boutiques à moderniser"],
      faq: [
        { q: "Quelle plateforme e-commerce choisir au Maroc ?", a: "Le choix dépend du catalogue, des intégrations, du budget et de l’autonomie attendue. Nous comparons les solutions prêtes à l’emploi et le sur-mesure avant de recommander l’architecture la plus rationnelle." },
        { q: "Pouvez-vous intégrer le paiement en ligne ?", a: "Oui, selon l’éligibilité de votre entreprise et les prestataires disponibles. Le paiement à la livraison ou d’autres modes peuvent aussi être intégrés au parcours." },
        { q: "Comment gérer la livraison ?", a: "Nous structurons les zones, tarifs et méthodes de livraison selon vos partenaires. Des connexions plus avancées sont possibles lorsque le transporteur fournit les outils nécessaires." },
        { q: "Le site pourra-t-il évoluer ?", a: "Oui. Nous anticipons les variantes, promotions, contenus et intégrations prioritaires afin d’éviter une reconstruction quand l’activité grandit." },
      ],
    },
    ar: {
      name: "متاجر إلكترونية",
      metaTitle: "تصميم متجر إلكتروني في المغرب",
      metaDescription: "تصميم متاجر إلكترونية سريعة في المغرب: كتالوج وطلب ودفع وتوصيل ولوحة إدارة مناسبة لطريقة عمل مشروعك.",
      eyebrow: "التجارة الإلكترونية · البيع عبر الإنترنت",
      title: "تصميم متجر إلكتروني في المغرب",
      highlight: "متجر سهل للشراء والإدارة وقابل للتوسع مع نمو النشاط.",
      description: "نبني تجربة تجارة إلكترونية مناسبة للسوق المغربي، من الكتالوج وصفحة المنتج إلى الطلب والدفع والتوصيل والإدارة اليومية.",
      introTitle: "النتيجة التجارية تعتمد على الرحلة كاملة",
      intro: [
        "المتجر الجيد يقلل التردد في كل خطوة: إيجاد المنتج وفهم العرض ومعرفة التوصيل ثم إنهاء الطلب من دون مفاجآت. نصمم المسار حسب منتجاتك وطريقة عملك الحقيقية.",
        "يعتمد الحل التقني على حجم الكتالوج والطلبات ووسائل الدفع والتوصيل والأدوات الداخلية. نتجنب التعقيد غير الضروري ونبني قاعدة موثوقة يسهل على فريقك إدارتها.",
      ],
      benefits: [
        { title: "شراء من دون تعقيد", text: "بحث وفئات وصفحات منتج وسلة وطلب منظمة لتجربة الهاتف." },
        { title: "إدارة مناسبة", text: "كتالوج ومخزون وطلبات ومحتوى منظم حسب طريقة عمل الفريق." },
        { title: "قاعدة قابلة للتوسع", text: "هندسة تسمح بإضافة منتجات ووسائل دفع وناقلين وأتمتة جديدة." },
      ],
      deliverables: ["الكتالوج والفئات", "صفحات المنتجات", "السلة والطلب", "وسيلة الدفع", "إدارة الطلبات", "تحليلات المتجر"],
      process: [
        { title: "نموذج البيع", text: "نحدد المنتجات والخيارات والأسعار والمخزون والدفع والتوصيل وقواعد التشغيل." },
        { title: "رحلة العميل", text: "نصمم التصفح والبحث وصفحة المنتج والسلة ومراحل الطلب على الهاتف." },
        { title: "الربط", text: "نربط الخدمات الضرورية ونجهز الإدارة اليومية للمتجر." },
        { title: "الاختبار والإطلاق", text: "نجرب سيناريوهات الطلب ونراجع الأداء والقياس ونواكب الفريق." },
      ],
      audiences: ["العلامات ذات الكتالوج", "المتاجر التي تنتقل إلى الإنترنت", "مشاريع البيع المباشر", "المتاجر التي تحتاج تحديثاً"],
      faq: [
        { q: "ما المنصة المناسبة للمتجر في المغرب؟", a: "يعتمد الاختيار على الكتالوج والربط والميزانية والاستقلالية المطلوبة. نقارن الحلول الجاهزة والتطوير المخصص قبل اقتراح الهندسة الأكثر منطقية." },
        { q: "هل يمكن دمج الدفع الإلكتروني؟", a: "نعم، حسب أهلية الشركة والخدمات المتاحة. ويمكن أيضاً دمج الدفع عند الاستلام أو وسائل أخرى ضمن المسار." },
        { q: "كيف تتم إدارة التوصيل؟", a: "ننظم المناطق والأسعار وطرق التوصيل حسب شركائك. ويمكن إضافة ربط متقدم عندما توفر شركة النقل الأدوات اللازمة." },
        { q: "هل يمكن للمتجر أن يتوسع؟", a: "نعم. نخطط للخيارات والعروض والمحتوى والربط المهم لتجنب إعادة البناء عند نمو النشاط." },
      ],
    },
  },
  {
    slug: "seo-maroc",
    icon: "Search",
    related: ["creation-site-web-maroc", "landing-page-maroc", "maintenance-site-web"],
    fr: {
      name: "SEO & visibilité",
      metaTitle: "Agence SEO au Maroc — Référencement naturel",
      metaDescription: "Accompagnement SEO au Maroc : audit technique, stratégie de contenu, SEO local et mesure pour développer une visibilité organique durable.",
      eyebrow: "SEO · Référencement naturel au Maroc",
      title: "Accompagnement SEO au Maroc",
      highlight: "Construire une visibilité utile auprès des personnes qui cherchent déjà vos services.",
      description: "Nous identifions les recherches pertinentes pour votre activité, corrigeons les obstacles techniques et construisons un plan de contenu local capable de générer un trafic plus qualifié.",
      introTitle: "Le SEO relie une intention de recherche à la bonne réponse",
      intro: [
        "Être visible ne consiste pas à répéter des mots-clés. Une page doit répondre précisément à une question, démontrer l’expertise de l’entreprise et offrir une expérience technique solide sur mobile comme sur ordinateur.",
        "Notre travail combine audit, architecture, contenu, données structurées et mesure. Les priorités sont choisies selon la valeur commerciale, la concurrence et les ressources disponibles, sans promesse artificielle de première position.",
      ],
      benefits: [
        { title: "Priorités claires", text: "Un audit traduit en actions classées par impact, effort et lien avec vos objectifs commerciaux." },
        { title: "Contenu utile", text: "Pages services et contenus éditoriaux construits autour des questions et intentions réelles." },
        { title: "Mesure durable", text: "Suivi de l’indexation, des requêtes, des pages d’entrée et des conversions organiques." },
      ],
      deliverables: ["Audit SEO technique", "Recherche d’intentions", "Architecture éditoriale", "Optimisation on-page", "Données structurées", "Suivi Search Console"],
      process: [
        { title: "Diagnostic", text: "Exploration, indexation, performances, contenus, concurrence et mesure existante." },
        { title: "Stratégie", text: "Regroupement des intentions et priorisation des pages qui soutiennent le mieux l’activité." },
        { title: "Optimisation", text: "Corrections techniques, amélioration des pages et création des contenus manquants." },
        { title: "Apprentissage", text: "Lecture des données, mise à jour des priorités et amélioration continue des pages utiles." },
      ],
      audiences: ["Entreprises locales", "Services B2B", "E-commerce", "Sites qui génèrent peu de trafic qualifié"],
      faq: [
        { q: "Combien de temps faut-il pour obtenir des résultats SEO ?", a: "Le délai varie selon l’état du site, la concurrence, le contenu et l’autorité du domaine. Les corrections techniques peuvent être rapides, tandis que la croissance organique demande généralement un travail continu et des données suffisantes." },
        { q: "Pouvez-vous garantir la première position ?", a: "Non. Aucun prestataire sérieux ne contrôle l’algorithme ou les actions des concurrents. Nous garantissons une méthode transparente, des optimisations conformes et un suivi des indicateurs utiles." },
        { q: "Le SEO local est-il inclus ?", a: "Il peut faire partie de la stratégie : pages locales utiles, cohérence des informations, Google Business Profile et contenu lié à votre zone de service." },
        { q: "Faut-il publier des articles ?", a: "Pas systématiquement. Nous privilégions d’abord les pages qui répondent à une intention commerciale. Les articles servent ensuite les questions importantes qui ne trouvent pas leur place dans une page service." },
      ],
    },
    ar: {
      name: "SEO والظهور",
      metaTitle: "خدمات SEO وتحسين الظهور في المغرب",
      metaDescription: "خدمات SEO في المغرب: تدقيق تقني واستراتيجية محتوى وSEO محلي وقياس لبناء ظهور عضوي مستدام وجلب زيارات أكثر صلة.",
      eyebrow: "SEO · تحسين محركات البحث في المغرب",
      title: "خدمات SEO في المغرب",
      highlight: "بناء ظهور مفيد أمام الأشخاص الذين يبحثون فعلاً عن خدماتك.",
      description: "نحدد عمليات البحث المهمة لنشاطك، نعالج العوائق التقنية ونبني خطة محتوى محلية تساعد على جلب زيارات أكثر صلة بالمشروع.",
      introTitle: "SEO يربط نية البحث بالإجابة المناسبة",
      intro: [
        "الظهور لا يعني تكرار الكلمات المفتاحية. يجب أن تجيب الصفحة بدقة عن سؤال المستخدم وتثبت خبرة الشركة وتقدم تجربة تقنية قوية على الهاتف والحاسوب.",
        "نجمع بين التدقيق والهندسة والمحتوى والبيانات المنظمة والقياس. نرتب الأولويات حسب القيمة التجارية والمنافسة والموارد المتاحة من دون وعود غير واقعية بالمركز الأول.",
      ],
      benefits: [
        { title: "أولويات واضحة", text: "تدقيق يتحول إلى خطوات مرتبة حسب التأثير والمجهود وعلاقتها بأهداف المشروع." },
        { title: "محتوى مفيد", text: "صفحات خدمات ومحتوى تحريري مبني حول الأسئلة ونيات البحث الحقيقية." },
        { title: "قياس مستمر", text: "متابعة الفهرسة وطلبات البحث وصفحات الدخول والتحويلات العضوية." },
      ],
      deliverables: ["تدقيق SEO تقني", "بحث نيات المستخدم", "هندسة المحتوى", "تحسين الصفحات", "بيانات منظمة", "متابعة Search Console"],
      process: [
        { title: "التشخيص", text: "نراجع الزحف والفهرسة والأداء والمحتوى والمنافسة والقياس الحالي." },
        { title: "الاستراتيجية", text: "نجمع نيات البحث ونرتب الصفحات الأكثر دعماً للنشاط." },
        { title: "التحسين", text: "إصلاحات تقنية وتطوير الصفحات وإنشاء المحتوى الناقص." },
        { title: "التعلم", text: "قراءة البيانات وتحديث الأولويات وتحسين الصفحات المفيدة باستمرار." },
      ],
      audiences: ["المشاريع المحلية", "خدمات B2B", "المتاجر الإلكترونية", "المواقع ذات الزيارات غير المؤهلة"],
      faq: [
        { q: "كم يحتاج SEO لظهور النتائج؟", a: "يختلف الوقت حسب حالة الموقع والمنافسة والمحتوى وقوة النطاق. يمكن تنفيذ الإصلاحات التقنية بسرعة، أما النمو العضوي فيحتاج عادة عملاً مستمراً وبيانات كافية." },
        { q: "هل تضمنون المركز الأول؟", a: "لا. لا يمكن لأي جهة التحكم في الخوارزمية أو المنافسين. ما نضمنه هو منهج واضح وتحسينات سليمة ومتابعة مؤشرات مفيدة." },
        { q: "هل يشمل العمل SEO المحلي؟", a: "يمكن أن يشمله: صفحات محلية مفيدة وتناسق المعلومات وGoogle Business Profile ومحتوى مرتبط بمنطقة الخدمة." },
        { q: "هل يجب نشر مقالات؟", a: "ليس دائماً. نبدأ بالصفحات التي تستجيب لنية تجارية، ثم نستخدم المقالات للأسئلة المهمة التي لا تناسب صفحة الخدمة." },
      ],
    },
  },
  {
    slug: "maintenance-site-web",
    icon: "Wrench",
    related: ["creation-site-web-maroc", "seo-maroc", "backend-api"],
    fr: {
      name: "Maintenance",
      metaTitle: "Maintenance de site web au Maroc",
      metaDescription: "Maintenance de sites web au Maroc : mises à jour, sécurité, sauvegardes, monitoring et améliorations continues pour garder un site fiable.",
      eyebrow: "Maintenance web · Sécurité & continuité",
      title: "Maintenance de site web au Maroc",
      highlight: "Un site surveillé, mis à jour et prêt à accompagner votre activité.",
      description: "Nous assurons le suivi technique de votre site pour réduire les interruptions, corriger les problèmes, maintenir les dépendances et faire évoluer les fonctionnalités utiles.",
      introTitle: "La mise en ligne n’est pas la fin du projet",
      intro: [
        "Les navigateurs, bibliothèques, intégrations et besoins métier évoluent. Sans suivi, de petites anomalies peuvent devenir des problèmes de sécurité, de performance ou de conversion.",
        "La maintenance est organisée selon la criticité du site et votre rythme d’évolution. Vous disposez d’un point de contact clair, d’un historique des interventions et d’une base plus prévisible pour les améliorations.",
      ],
      benefits: [
        { title: "Risque réduit", text: "Mises à jour suivies, contrôles essentiels et sauvegardes adaptées à l’architecture du projet." },
        { title: "Performance surveillée", text: "Détection des erreurs, liens cassés ou ralentissements avant qu’ils n’affectent durablement les visiteurs." },
        { title: "Évolutions cadrées", text: "Petites améliorations et nouvelles demandes priorisées selon leur impact réel." },
      ],
      deliverables: ["Mises à jour techniques", "Sauvegardes", "Monitoring", "Corrections de bugs", "Contrôles de sécurité", "Rapport d’intervention"],
      process: [
        { title: "Audit initial", text: "Technologies, hébergement, accès, dépendances, sauvegardes et problèmes connus." },
        { title: "Plan de suivi", text: "Fréquence, périmètre, priorités et méthode de remontée des demandes." },
        { title: "Maintenance", text: "Mises à jour contrôlées, vérifications, corrections et tests des parcours essentiels." },
        { title: "Amélioration", text: "Bilan régulier et recommandations selon les incidents, usages et objectifs du site." },
      ],
      audiences: ["Sites vitrines actifs", "Boutiques e-commerce", "Applications métier", "Équipes sans ressource technique interne"],
      faq: [
        { q: "Que comprend un contrat de maintenance ?", a: "Le périmètre peut inclure mises à jour, sauvegardes, monitoring, corrections et temps d’évolution. Il est défini selon la technologie et la criticité de votre site." },
        { q: "Pouvez-vous maintenir un site que vous n’avez pas créé ?", a: "Oui, après un audit technique. Celui-ci permet de vérifier la qualité du code, les accès, la documentation et les risques avant de confirmer le périmètre." },
        { q: "La maintenance protège-t-elle contre toutes les attaques ?", a: "Aucun système ne garantit un risque nul. Une maintenance sérieuse réduit l’exposition grâce aux mises à jour, sauvegardes, contrôles et bonnes pratiques adaptées." },
        { q: "Pouvez-vous ajouter de nouvelles fonctionnalités ?", a: "Oui. Les évolutions sont estimées et priorisées séparément ou intégrées à une enveloppe prévue, selon leur taille et leur impact." },
      ],
    },
    ar: {
      name: "الصيانة والدعم",
      metaTitle: "صيانة المواقع الإلكترونية في المغرب",
      metaDescription: "صيانة المواقع في المغرب: تحديثات وأمان ونسخ احتياطي ومراقبة وتحسينات مستمرة للحفاظ على موقع موثوق وسريع.",
      eyebrow: "صيانة المواقع · الأمان والاستمرارية",
      title: "صيانة المواقع الإلكترونية في المغرب",
      highlight: "موقع مراقب ومحدث وجاهز لمواكبة تطور نشاطك.",
      description: "نتابع الجانب التقني للموقع لتقليل التوقفات ومعالجة المشاكل وتحديث الاعتماديات وتطوير الوظائف المفيدة.",
      introTitle: "إطلاق الموقع ليس نهاية المشروع",
      intro: [
        "تتغير المتصفحات والمكتبات وخدمات الربط وحاجات النشاط. من دون متابعة، يمكن لمشكلة صغيرة أن تتحول إلى خطر أمني أو بطء أو فقدان للتحويلات.",
        "ننظم الصيانة حسب أهمية الموقع وسرعة تطوره. تحصل على نقطة تواصل واضحة وسجل للتدخلات وقاعدة أكثر استقراراً للتحسينات.",
      ],
      benefits: [
        { title: "تقليل المخاطر", text: "تحديثات مراقبة وفحوصات أساسية ونسخ احتياطي مناسب لهندسة المشروع." },
        { title: "مراقبة الأداء", text: "اكتشاف الأخطاء والروابط المعطلة والبطء قبل تأثيرها المستمر على الزوار." },
        { title: "تطوير منظم", text: "ترتيب التحسينات والطلبات الجديدة حسب تأثيرها الحقيقي." },
      ],
      deliverables: ["تحديثات تقنية", "نسخ احتياطي", "مراقبة", "إصلاح الأخطاء", "فحوصات الأمان", "تقارير التدخل"],
      process: [
        { title: "التدقيق الأولي", text: "نراجع التقنية والاستضافة والصلاحيات والاعتماديات والنسخ الاحتياطي والمشاكل المعروفة." },
        { title: "خطة المتابعة", text: "نحدد التكرار والنطاق والأولويات وطريقة إرسال الطلبات." },
        { title: "الصيانة", text: "تحديثات مضبوطة وفحوصات وإصلاحات واختبار للمسارات الأساسية." },
        { title: "التحسين", text: "مراجعة دورية وتوصيات حسب المشاكل والاستعمال وأهداف الموقع." },
      ],
      audiences: ["مواقع الشركات النشطة", "المتاجر الإلكترونية", "تطبيقات الأعمال", "الفرق من دون مورد تقني داخلي"],
      faq: [
        { q: "ماذا تشمل صيانة الموقع؟", a: "يمكن أن تشمل التحديثات والنسخ الاحتياطي والمراقبة والإصلاحات ووقت التطوير. نحدد النطاق حسب التقنية وأهمية الموقع." },
        { q: "هل يمكن صيانة موقع لم تقوموا بتطويره؟", a: "نعم بعد تدقيق تقني للتأكد من جودة الكود والصلاحيات والتوثيق والمخاطر قبل تحديد النطاق." },
        { q: "هل تمنع الصيانة كل الهجمات؟", a: "لا يوجد نظام بدون مخاطر. الصيانة الجيدة تقلل التعرض عبر التحديثات والنسخ الاحتياطي والفحوصات والممارسات المناسبة." },
        { q: "هل يمكن إضافة وظائف جديدة؟", a: "نعم. نقيم التطويرات ونرتبها بشكل منفصل أو ضمن وقت مخصص حسب الحجم والتأثير." },
      ],
    },
  },
  {
    slug: "application-web-sur-mesure",
    icon: "LayoutDashboard",
    related: ["backend-api", "ui-ux-identite-visuelle", "maintenance-site-web"],
    fr: {
      name: "Applications web",
      metaTitle: "Développement d’application web au Maroc",
      metaDescription: "Développement d’applications web sur mesure au Maroc : dashboards, portails clients et outils métier rapides, sécurisés et adaptés à vos processus.",
      eyebrow: "Applications web · Outils métier sur mesure",
      title: "Développement d’application web au Maroc",
      highlight: "Un outil construit autour de vos processus, pas l’inverse.",
      description: "Nous développons des dashboards, portails clients et plateformes métier qui centralisent l’information, simplifient les opérations et donnent une vue claire aux utilisateurs.",
      introTitle: "Transformer un processus complexe en outil simple",
      intro: [
        "Les feuilles de calcul dispersées, tâches répétitives et échanges manuels ralentissent les équipes. Une application web bien cadrée centralise les données et rend chaque rôle plus autonome.",
        "Nous commençons par le processus et les décisions importantes, puis construisons uniquement les fonctionnalités nécessaires. Cette approche réduit la complexité, accélère l’adoption et facilite les évolutions futures.",
      ],
      benefits: [
        { title: "Processus centralisés", text: "Données, statuts et actions regroupés dans une interface adaptée aux différents rôles." },
        { title: "Moins de tâches manuelles", text: "Automatisations ciblées pour réduire les doubles saisies et les étapes répétitives." },
        { title: "Décisions plus lisibles", text: "Tableaux de bord et filtres conçus autour des indicateurs réellement utilisés." },
      ],
      deliverables: ["Cadrage fonctionnel", "UX de l’application", "Authentification", "Dashboard", "Gestion des rôles", "Documentation"],
      process: [
        { title: "Découverte métier", text: "Acteurs, tâches, données, règles, irritants et décisions prioritaires." },
        { title: "Prototype", text: "Parcours et écrans essentiels validés avant d’investir dans le développement complet." },
        { title: "Construction progressive", text: "Fonctionnalités livrées par blocs testables avec des retours réguliers des utilisateurs." },
        { title: "Déploiement & adoption", text: "Tests, sécurité, mise en ligne, accompagnement et plan d’évolution." },
      ],
      audiences: ["Équipes opérationnelles", "Portails clients ou partenaires", "SaaS en phase de validation", "Entreprises qui veulent remplacer des processus manuels"],
      faq: [
        { q: "Quelle différence avec un site web classique ?", a: "Un site présente principalement de l’information. Une application permet aux utilisateurs de se connecter, manipuler des données et accomplir des tâches selon des règles métier." },
        { q: "Faut-il développer toutes les fonctionnalités dès le début ?", a: "Non. Nous recommandons un premier périmètre utile qui valide le processus, puis des évolutions guidées par les usages réels." },
        { q: "Pouvez-vous gérer plusieurs types d’utilisateurs ?", a: "Oui. Les rôles et permissions sont définis selon les responsabilités afin que chaque utilisateur accède uniquement aux informations et actions nécessaires." },
        { q: "Comment sont protégées les données ?", a: "La sécurité est traitée à plusieurs niveaux : authentification, permissions, validation, stockage et suivi. Les mesures exactes dépendent de la sensibilité et de l’architecture du projet." },
      ],
    },
    ar: {
      name: "تطبيقات الويب",
      metaTitle: "تطوير تطبيقات ويب في المغرب",
      metaDescription: "تطوير تطبيقات ويب مخصصة في المغرب: لوحات قيادة وبوابات عملاء وأدوات أعمال سريعة وآمنة ومناسبة لعمليات شركتك.",
      eyebrow: "تطبيقات الويب · أدوات أعمال مخصصة",
      title: "تطوير تطبيقات ويب في المغرب",
      highlight: "أداة مبنية حول طريقة عملك، وليس العكس.",
      description: "نطور لوحات قيادة وبوابات عملاء ومنصات أعمال تجمع المعلومات وتبسط العمليات وتوفر رؤية واضحة لكل مستخدم.",
      introTitle: "تحويل عملية معقدة إلى أداة بسيطة",
      intro: [
        "جداول البيانات المتفرقة والمهام المتكررة والتواصل اليدوي تبطئ الفرق. التطبيق الجيد يجمع البيانات ويمنح كل دور استقلالية أكبر.",
        "نبدأ من العملية والقرارات المهمة، ثم نبني الوظائف الضرورية فقط. هذا يقلل التعقيد ويسرع التبني ويسهل التطوير مستقبلاً.",
      ],
      benefits: [
        { title: "عمليات مركزية", text: "بيانات وحالات وإجراءات داخل واجهة مناسبة لمختلف الأدوار." },
        { title: "عمل يدوي أقل", text: "أتمتة مركزة تقلل الإدخال المكرر والمراحل الروتينية." },
        { title: "قرارات أوضح", text: "لوحات قيادة وفلاتر مبنية حول المؤشرات المستخدمة فعلاً." },
      ],
      deliverables: ["تحديد الوظائف", "UX التطبيق", "تسجيل الدخول", "لوحة القيادة", "إدارة الصلاحيات", "التوثيق"],
      process: [
        { title: "فهم العمل", text: "نحدد الأطراف والمهام والبيانات والقواعد والمشاكل والقرارات المهمة." },
        { title: "النموذج", text: "نراجع المسارات والشاشات الأساسية قبل الاستثمار في التطوير الكامل." },
        { title: "بناء تدريجي", text: "نسلم الوظائف على مراحل قابلة للاختبار مع ملاحظات دورية من المستخدمين." },
        { title: "الإطلاق والتبني", text: "اختبارات وأمان ونشر ومواكبة وخطة للتطوير." },
      ],
      audiences: ["فرق العمليات", "بوابات العملاء والشركاء", "مشاريع SaaS قيد الاختبار", "شركات تريد تعويض العمليات اليدوية"],
      faq: [
        { q: "ما الفرق بين التطبيق والموقع؟", a: "الموقع يقدم المعلومات أساساً، أما التطبيق فيسمح للمستخدم بالدخول والتعامل مع البيانات وتنفيذ مهام حسب قواعد العمل." },
        { q: "هل يجب تطوير كل الوظائف من البداية؟", a: "لا. نوصي بنطاق أول مفيد يختبر العملية، ثم تطويرات موجهة حسب الاستعمال الحقيقي." },
        { q: "هل يمكن إدارة عدة أنواع من المستخدمين؟", a: "نعم. نحدد الأدوار والصلاحيات حسب المسؤوليات ليصل كل مستخدم إلى المعلومات والإجراءات اللازمة فقط." },
        { q: "كيف تتم حماية البيانات؟", a: "نتعامل مع الأمان عبر تسجيل الدخول والصلاحيات والتحقق والتخزين والمتابعة. التدابير الدقيقة تعتمد على حساسية البيانات وهندسة المشروع." },
      ],
    },
  },
  {
    slug: "backend-api",
    icon: "Server",
    related: ["application-web-sur-mesure", "ecommerce-maroc", "maintenance-site-web"],
    fr: {
      name: "Backend & API",
      metaTitle: "Développement backend & API au Maroc",
      metaDescription: "Développement backend et API au Maroc : architecture, bases de données, intégrations et authentification pour applications fiables et évolutives.",
      eyebrow: "Backend · API & intégrations",
      title: "Développement backend et API au Maroc",
      highlight: "Une infrastructure fiable pour connecter vos données et faire évoluer vos produits.",
      description: "Nous développons les services backend, APIs et intégrations qui alimentent vos sites, applications métier et expériences e-commerce avec une architecture claire et maintenable.",
      introTitle: "Le backend organise les règles et la donnée du produit",
      intro: [
        "Quand plusieurs interfaces, utilisateurs ou services partagent les mêmes données, une architecture improvisée crée rapidement des incohérences. Le backend doit définir clairement les règles, les accès et les échanges.",
        "Nous choisissons les technologies selon le volume, la sensibilité, les intégrations et les compétences disponibles. La documentation et l’observabilité font partie du travail pour rendre la solution exploitable après la livraison.",
      ],
      benefits: [
        { title: "Données cohérentes", text: "Modèles, validations et règles métier centralisés pour limiter les erreurs entre systèmes." },
        { title: "Intégrations maîtrisées", text: "APIs internes ou externes connectées avec gestion des erreurs et suivi des échanges." },
        { title: "Évolution prévisible", text: "Architecture modulaire, documentation et tests ciblés pour faire grandir le produit." },
      ],
      deliverables: ["Architecture backend", "Modèle de données", "API REST", "Authentification", "Intégrations tierces", "Documentation technique"],
      process: [
        { title: "Contraintes & flux", text: "Sources de données, acteurs, volumes, sécurité, intégrations et disponibilité attendue." },
        { title: "Conception", text: "Modèles, endpoints, permissions, traitements et stratégie de gestion des erreurs." },
        { title: "Développement & tests", text: "Construction par modules, validations, tests des cas critiques et documentation." },
        { title: "Déploiement & suivi", text: "Environnements, logs, monitoring et procédure d’évolution ou d’incident." },
      ],
      audiences: ["Applications web et mobiles", "Plateformes e-commerce", "Systèmes à connecter", "Produits qui dépassent les limites d’un backend existant"],
      faq: [
        { q: "Qu’est-ce qu’une API ?", a: "Une API définit comment plusieurs logiciels échangent des données et déclenchent des actions. Elle permet par exemple de relier un site, une application, un paiement ou un outil interne." },
        { q: "Pouvez-vous reprendre un backend existant ?", a: "Oui, après analyse du code, de la base de données, de la documentation et des environnements. Nous identifions les risques avant de proposer une reprise progressive." },
        { q: "Quelle base de données utilisez-vous ?", a: "Le choix dépend de la structure des données, des requêtes, du volume et de l’écosystème. Nous pouvons travailler avec des solutions relationnelles ou documentaires selon le besoin." },
        { q: "Comment préparez-vous la montée en charge ?", a: "Nous commençons par des mesures réalistes, une architecture modulaire, des requêtes efficaces et de l’observabilité. La complexité d’infrastructure n’est ajoutée que lorsqu’elle répond à un besoin mesuré." },
      ],
    },
    ar: {
      name: "Backend وAPI",
      metaTitle: "تطوير Backend وAPI في المغرب",
      metaDescription: "تطوير Backend وAPI في المغرب: هندسة وقواعد بيانات وربط وتسجيل دخول لتطبيقات موثوقة وقابلة للتوسع.",
      eyebrow: "Backend · API والربط",
      title: "تطوير Backend وAPI في المغرب",
      highlight: "بنية موثوقة تربط بياناتك وتسمح لمنتجك بالتطور.",
      description: "نطور خدمات Backend وواجهات API والربط الذي يشغل المواقع وتطبيقات الأعمال والمتاجر ضمن هندسة واضحة وسهلة الصيانة.",
      introTitle: "الـBackend ينظم قواعد المنتج وبياناته",
      intro: [
        "عندما تشارك عدة واجهات ومستخدمين وخدمات نفس البيانات، تؤدي الهندسة غير المنظمة إلى أخطاء وتناقضات. يجب أن يحدد الـBackend القواعد والصلاحيات والتبادل بوضوح.",
        "نختار التقنية حسب الحجم والحساسية والربط والمهارات المتاحة. كما نهتم بالتوثيق والمراقبة لتبقى المنظومة قابلة للإدارة بعد التسليم.",
      ],
      benefits: [
        { title: "بيانات متناسقة", text: "نماذج وتحقق وقواعد أعمال مركزية لتقليل الأخطاء بين الأنظمة." },
        { title: "ربط منظم", text: "ربط APIs داخلية وخارجية مع إدارة الأخطاء ومتابعة التبادل." },
        { title: "توسع متوقع", text: "هندسة مرنة وتوثيق واختبارات مركزة لتطوير المنتج." },
      ],
      deliverables: ["هندسة Backend", "نموذج البيانات", "REST API", "تسجيل الدخول", "ربط خدمات خارجية", "توثيق تقني"],
      process: [
        { title: "القيود والتدفقات", text: "نحدد مصادر البيانات والأطراف والحجم والأمان والربط والتوفر المطلوب." },
        { title: "التصميم", text: "نماذج وendpoints وصلاحيات ومعالجات واستراتيجية إدارة الأخطاء." },
        { title: "التطوير والاختبار", text: "بناء على وحدات والتحقق واختبار الحالات المهمة والتوثيق." },
        { title: "النشر والمتابعة", text: "بيئات وlogs ومراقبة وطريقة واضحة للتطوير أو معالجة المشاكل." },
      ],
      audiences: ["تطبيقات الويب والهاتف", "منصات التجارة الإلكترونية", "أنظمة تحتاج الربط", "منتجات تجاوزت حدود backend الحالي"],
      faq: [
        { q: "ما هي API؟", a: "API تحدد طريقة تبادل البيانات وتنفيذ الإجراءات بين البرامج، مثل ربط الموقع بالتطبيق أو الدفع أو أداة داخلية." },
        { q: "هل يمكنكم تطوير Backend موجود؟", a: "نعم بعد تحليل الكود وقاعدة البيانات والتوثيق والبيئات، ثم نحدد المخاطر ونقترح استلاماً تدريجياً." },
        { q: "ما قاعدة البيانات التي تستخدمونها؟", a: "يعتمد الاختيار على شكل البيانات والاستعلامات والحجم والتقنيات. نعمل بحلول علائقية أو وثائقية حسب الحاجة." },
        { q: "كيف تستعدون لزيادة الاستعمال؟", a: "نبدأ بقياسات واقعية وهندسة مرنة واستعلامات فعالة ومراقبة. لا نضيف تعقيداً في البنية إلا عند وجود حاجة مقاسة." },
      ],
    },
  },
]

export const serviceSlugs = serviceCatalog.map((service) => service.slug)

export function getServiceBySlug(slug) {
  return serviceCatalog.find((service) => service.slug === slug)
}
