import { branding } from "./services/branding"
import { designGraphique } from "./services/design-graphique"
import { photoVideo } from "./services/photo-video"
import { socialMedia } from "./services/social-media"
import { marketingInfluence } from "./services/marketing-influence"
import { publicitePayante } from "./services/publicite-payante"
import { emailMarketing } from "./services/email-marketing"

export const serviceCatalog = [
  branding,
  designGraphique,
  photoVideo,
  socialMedia,
  marketingInfluence,
  publicitePayante,
  emailMarketing,
  {
    slug: "creation-site-web-maroc",
    icon: "Code",
    related: ["ui-ux-identite-visuelle", "landing-page-maroc", "seo-maroc"],
    fr: {
      name: "Sites web premium",
      metaTitle: "Création site web Casablanca | Agence web au Maroc",
      metaDescription: "Création de site web professionnel à Casablanca : sites vitrines et corporate rapides, optimisés SEO et pensés pour générer des contacts au Maroc.",
      eyebrow: "Création de sites web · Casablanca & Maroc",
      title: "Création de site web professionnel à Casablanca",
      highlight: "Une présence digitale qui inspire confiance et génère des contacts.",
      description: "Nous concevons des sites vitrines et corporate rapides, clairs et faciles à faire évoluer pour les entreprises de Casablanca et du Maroc qui veulent présenter leur valeur et convertir davantage de visiteurs en contacts.",
      introTitle: "Votre site doit travailler pour votre activité",
      intro: [
        "Un beau site ne suffit pas. Il doit expliquer votre offre en quelques secondes, rassurer le visiteur et lui donner une prochaine action évidente. Nous réunissons stratégie, contenu, design UI/UX et développement pour construire ce parcours sans friction.",
        "Chaque page est pensée pour le mobile, la vitesse et le référencement naturel. L’architecture reste claire pour Google comme pour vos prospects, tandis que le design traduit la personnalité de votre marque sans sacrifier la lisibilité.",
      ],
      showcase: {
        title: "Création de site vitrine à Casablanca",
        text: [
          "Un site vitrine présente votre entreprise, vos services et vos réalisations, puis conduit le visiteur vers une demande de contact. C’est le format de référence pour les entreprises de services, les commerces de proximité, les restaurants et les professions libérales à Casablanca qui n’ont pas besoin de vendre en ligne, mais doivent exister de manière crédible là leurs clients les cherchent.",
          "Nous construisons ces sites autour de quatre piliers : une présentation claire de l’activité et de l’équipe, des services structurés pour la lecture comme pour Google, des formulaires et contacts directs faciles à trouver, et une expérience mobile fluide. L’architecture est prête pour le référencement naturel dès la mise en ligne, sans réécriture ultérieure.",
        ],
      },
      benefits: [
        { title: "Crédibilité immédiate", text: "Une direction visuelle cohérente et un message précis pour donner confiance dès la première visite." },
        { title: "Performance durable", text: "Une base Next.js rapide, responsive et structurée pour les Core Web Vitals et le SEO technique." },
        { title: "Conversion claire", text: "Des appels à l’action, preuves et formulaires placés selon le parcours réel de vos futurs clients." },
      ],
      deliverables: ["Architecture des pages", "Design responsive", "Développement Next.js", "SEO technique", "Connexion WhatsApp", "Mesure des conversions"],
      process: [
        { title: "Cadrage", text: "Objectifs, audience, concurrence, contenus disponibles et action principale attendue." },
        { title: "UX & direction visuelle", text: "Structure des pages, hiérarchie du message et interface alignée avec votre identité." },
        { title: "Développement", text: "Intégration responsive, animations utiles, optimisation des images et des performances." },
        { title: "Mise en ligne", text: "Contrôles techniques, indexation, analytics et prise en main de votre nouveau site." },
      ],
      audiences: ["PME et entreprises de services", "Cabinets et professions libérales", "Commerces de proximité et restaurants", "Marques premium", "Projets en lancement ou en refonte"],
      faq: [
        { q: "Combien coûte un site web professionnel au Maroc ?", a: "Le tarif dépend du périmètre, du nombre de pages, du contenu et des fonctionnalités. Un devis est établi selon le projet, après un court échange pour préciser vos priorités commerciales." },
        { q: "Quel est le délai pour créer un site web ?", a: "Le délai dépend de la portée du projet, du nombre de pages, des contenus à fournir et des fonctionnalités attendues. Un site vitrine simple demande moins de temps qu’une plateforme multi-services. Nous vous indiquons une fourchette réaliste dès le cadrage." },
        { q: "Le site sera-t-il optimisé pour Google ?", a: "Oui. La structure sémantique, les métadonnées, la vitesse, le mobile, le sitemap et les données structurées font partie de la base. Le positionnement dépend ensuite aussi du contenu, de la concurrence et de l’autorité du domaine." },
        { q: "Pourrai-je modifier le contenu ?", a: "Oui. Le mode d’édition est choisi selon votre besoin : contenu intégré, CMS ou interface d’administration. Nous privilégions la solution la plus simple à maintenir pour votre équipe." },
        { q: "Pouvez-vous refaire un site existant ?", a: "Oui. Nous auditons les pages et URLs existantes, conservons ce qui apporte de la valeur puis améliorons l’expérience, la vitesse et le parcours de conversion. Une refonte permet aussi de conserver le référencement déjà acquis." },
        { q: "Assurez-vous la maintenance après la mise en ligne ?", a: "La mise en ligne inclut la vérification technique, l’indexation et la prise en main. Pour les mises à jour, la sécurité et les évolutions ultérieures, nous proposons un suivi adapté à votre site." },
      ],
    },
    en: {
      name: "Premium websites",
      metaTitle: "Website design in Casablanca | Web agency in Morocco",
      metaDescription: "Professional website design in Casablanca: fast brochure and corporate websites, SEO-ready and built to generate enquiries in Morocco.",
      eyebrow: "Website design · Casablanca & Morocco",
      title: "Professional website design in Casablanca",
      highlight: "A digital presence that inspires trust and generates enquiries.",
      description: "We design fast, clear and scalable brochure and corporate websites for businesses in Casablanca and across Morocco that want to present their value and turn more visitors into enquiries.",
      introTitle: "Your website should work for your business",
      intro: [
        "A beautiful website is not enough. It needs to explain your offer in seconds, reassure visitors and give them an obvious next step. We bring together strategy, content, UI/UX design and development to create a frictionless journey.",
        "Every page is designed for mobile, speed and organic search. The architecture stays clear for both Google and your prospects, while the design expresses your brand personality without sacrificing readability.",
      ],
      showcase: {
        title: "Brochure website design in Casablanca",
        text: [
          "A brochure website presents your business, services and work, then guides visitors towards a contact enquiry. It is the go-to format for service businesses, local shops, restaurants and independent professionals in Casablanca that do not need to sell online but need a credible presence where their customers are looking.",
          "We build these sites around four pillars: a clear presentation of the business and team, services structured for both readers and Google, easy-to-find forms and direct contact options, and a smooth mobile experience. The architecture is ready for organic search from launch, without a later rewrite.",
        ],
      },
      benefits: [
        { title: "Immediate credibility", text: "A consistent visual direction and precise message that build trust from the first visit." },
        { title: "Long-lasting performance", text: "A fast, responsive Next.js foundation structured for Core Web Vitals and technical SEO." },
        { title: "Clear conversion path", text: "Calls to action, proof points and forms placed around the real journey of your future customers." },
      ],
      deliverables: ["Page architecture", "Responsive design", "Next.js development", "Technical SEO", "WhatsApp connection", "Conversion measurement"],
      process: [
        { title: "Scoping", text: "Goals, audience, competitors, available content and the primary action expected from visitors." },
        { title: "UX & visual direction", text: "Page structure, message hierarchy and an interface aligned with your identity." },
        { title: "Development", text: "Responsive implementation, purposeful animations, image optimisation and performance improvements." },
        { title: "Launch", text: "Technical checks, indexing, analytics and a handover of your new website." },
      ],
      audiences: ["SMEs and service businesses", "Practices and independent professionals", "Local shops and restaurants", "Premium brands", "New or redesign projects"],
      faq: [
        { q: "How much does a professional website cost in Morocco?", a: "The cost depends on the scope, number of pages, content and functionality. We prepare a project-specific quote after a short discussion to clarify your commercial priorities." },
        { q: "How long does it take to build a website?", a: "The timeline depends on the project scope, page count, content to provide and required functionality. A simple brochure site takes less time than a multi-service platform. We give you a realistic range during scoping." },
        { q: "Will the website be optimised for Google?", a: "Yes. Semantic structure, metadata, speed, mobile readiness, sitemap and structured data are part of the foundation. Rankings then also depend on content, competition and domain authority." },
        { q: "Will I be able to edit the content?", a: "Yes. We choose the editing approach that fits your needs: built-in content, a CMS or an admin interface. We favour the solution that is easiest for your team to maintain." },
        { q: "Can you redesign an existing website?", a: "Yes. We audit the current pages and URLs, retain what creates value, then improve the experience, speed and conversion journey. A redesign can also preserve the search visibility you have already earned." },
        { q: "Do you provide maintenance after launch?", a: "Launch includes technical verification, indexing and a handover. For updates, security and future improvements, we offer support suited to your website." },
      ],
    },
  },
  {
    slug: "ui-ux-identite-visuelle",
    icon: "Palette",
    related: ["branding-identite-marque", "creation-site-web-maroc", "application-web-sur-mesure"],
    fr: {
      name: "Design UI/UX",
      metaTitle: "Design UI/UX à Casablanca | Interfaces web & applications",
      metaTitleAbsolute: true,
      metaDescription: "Design UI/UX à Casablanca : wireframes, parcours utilisateur, prototypes et interfaces responsive pour sites et applications au Maroc.",
      eyebrow: "Design UI/UX · Casablanca et Maroc",
      title: "Design UI/UX à Casablanca",
      highlight: "Des interfaces claires, des parcours lisibles et des règles réutilisables pour préparer le développement.",
      description: "À Casablanca, nous concevons des interfaces web et applications pour les entreprises au Maroc : parcours utilisateur, wireframes, prototypes et systèmes d’interface pensés pour le développement.",
      introTitle: "Concevoir une interface avant de la développer",
      intro: [
        "Un site ou une application doit aider chaque utilisateur à comprendre où il se trouve, ce qu’il peut faire et quelle action suivre. Nous clarifions les priorités du projet, les contenus et les écrans utiles avant de finaliser l’interface.",
        "Pour une création ou une refonte à Casablanca et au Maroc, nous organisons les parcours, les wireframes, les composants et les règles d’interface afin de préparer un développement plus cohérent sur tous les écrans.",
      ],
      benefits: [
        { title: "Parcours plus clairs", text: "Navigation, hiérarchie et actions organisées pour guider l’utilisateur d’un écran à l’autre." },
        { title: "Interfaces cohérentes", text: "Composants, états et règles d’interface réunis pour garder une expérience lisible sur le site ou l’application." },
        { title: "Préparation plus claire", text: "Des écrans, règles et composants réutilisables qui facilitent le passage au développement et les évolutions futures." },
      ],
      deliverables: ["Wireframes", "Parcours utilisateur", "Design d’interface", "Prototype interactif", "Règles de design system", "Guide de composants"],
      process: [
        { title: "Cadrage", text: "Objectifs du projet, écrans utiles, contenus prioritaires et contraintes à prendre en compte." },
        { title: "Structure", text: "Parcours, wireframes et hiérarchie des écrans avant de finaliser l’interface." },
        { title: "Système d’interface", text: "Composants, états, grilles et règles réutilisables pour des interfaces cohérentes." },
        { title: "Prototype & préparation", text: "Écrans interactifs, contrôles de cohérence et éléments organisés pour préparer le développement." },
      ],
      audiences: ["Entreprises qui lancent un site ou une application", "Sites dont l’interface manque de clarté", "Applications métier et outils numériques", "Équipes qui préparent une refonte"],
      faq: [
        { q: "Quelle est la différence entre UI et UX ?", a: "L’UX organise l’expérience, le parcours et la facilité d’usage. L’UI définit l’aspect visuel et les interactions. Les deux doivent avancer ensemble pour produire une interface utile et crédible." },
        { q: "Faut-il concevoir l’interface avant le développement ?", a: "Oui, lorsque le projet comporte plusieurs écrans, parcours ou actions. Les wireframes, écrans et règles d’interface permettent de clarifier ce qui doit être construit avant le développement." },
        { q: "Pouvez-vous améliorer l’interface d’un site ou d’une application existante ?", a: "Oui. Nous pouvons reprendre une interface existante pour clarifier les parcours, les écrans, la hiérarchie et la présentation responsive, sans la transformer en projet de développement." },
        { q: "Quels livrables recevons-nous pour préparer le développement ?", a: "Selon le périmètre, vous recevez les wireframes, parcours utilisateur, écrans d’interface, prototypes interactifs, règles de design system et guide de composants utiles au projet." },
      ],
      resources: [
        { id: "design-ux-maroc-2026", title: "Design UX au Maroc : créer des interfaces qui convertissent", description: "Principes mobile-first, accessibilité et parcours utilisateur pour les interfaces digitales." },
      ],
    },
    en: {
      name: "UI/UX Design",
      metaTitle: "UI/UX Design in Casablanca | Web & App Interfaces",
      metaTitleAbsolute: true,
      metaDescription: "UI/UX design in Casablanca: wireframes, user journeys, prototypes and responsive interfaces for websites and applications across Morocco.",
      eyebrow: "UI/UX Design · Casablanca and Morocco",
      title: "UI/UX Design in Casablanca",
      highlight: "Clear interfaces, understandable journeys and reusable rules that prepare a project for development.",
      description: "In Casablanca, we design web and application interfaces for businesses across Morocco: user journeys, wireframes, prototypes and interface systems prepared for development.",
      introTitle: "Design an interface before developing it",
      intro: [
        "A website or application should help every user understand where they are, what they can do and which action to take next. We clarify project priorities, content and useful screens before finalising the interface.",
        "For a new project or redesign in Casablanca and across Morocco, we organise journeys, wireframes, components and interface rules to prepare more consistent development across screen sizes.",
      ],
      benefits: [
        { title: "Clearer journeys", text: "Navigation, hierarchy and actions organised to guide users from one screen to the next." },
        { title: "Consistent interfaces", text: "Components, states and interface rules brought together to keep the website or application easy to understand." },
        { title: "Clearer preparation", text: "Reusable screens, rules and components that make the move into development and future updates easier." },
      ],
      deliverables: ["Wireframes", "User journeys", "Interface design", "Interactive prototype", "Design-system rules", "Component guide"],
      process: [
        { title: "Scoping", text: "Project goals, useful screens, priority content and constraints to take into account." },
        { title: "Structure", text: "Journeys, wireframes and screen hierarchy before finalising the interface." },
        { title: "Interface system", text: "Components, states, grids and reusable rules for consistent interfaces." },
        { title: "Prototype & preparation", text: "Interactive screens, consistency checks and organised elements to prepare development." },
      ],
      audiences: ["Businesses launching a website or application", "Websites with unclear interfaces", "Business applications and digital tools", "Teams preparing a redesign"],
      faq: [
        { q: "What is the difference between UI and UX?", a: "UX organises the experience, journey and ease of use. UI defines the visual appearance and interactions. Both need to move forward together to create a useful, credible interface." },
        { q: "Should the interface be designed before development?", a: "Yes, when a project includes several screens, journeys or actions. Wireframes, screens and interface rules clarify what needs to be built before development starts." },
        { q: "Can you improve an existing website or application interface?", a: "Yes. We can revisit an existing interface to clarify journeys, screens, hierarchy and responsive presentation without turning the work into a development project." },
        { q: "Which deliverables will we receive to prepare development?", a: "Depending on the scope, you receive wireframes, user journeys, interface screens, interactive prototypes, design-system rules and a component guide that are useful for the project." },
      ],
      resources: [
        { id: "design-ux-maroc-2026", title: "UX design in Morocco: creating interfaces that convert", description: "Mobile-first, accessibility and user-journey principles for digital interfaces." },
      ],
    },
  },
  {
    slug: "landing-page-maroc",
    icon: "MousePointer2",
    related: ["publicite-payante-maroc", "creation-site-web-maroc", "ui-ux-identite-visuelle"],
    fr: {
      name: "Landing pages",
      metaTitle: "Création de landing page à Casablanca | Campagnes au Maroc",
      metaTitleAbsolute: true,
      metaDescription: "Landing pages à Casablanca pour Meta Ads et Google Ads : message, structure de conversion, design responsive, GA4 et CTA formulaire ou WhatsApp.",
      eyebrow: "Landing pages · Casablanca et Maroc",
      title: "Création de landing page à Casablanca",
      highlight: "Une page concentrée sur une offre, une audience et une action.",
      description: "Nous créons des landing pages orientées conversion pour les entreprises de Casablanca et les campagnes menées au Maroc, afin de transformer le trafic en demandes qualifiées, prises de rendez-vous ou conversations WhatsApp.",
      introTitle: "Chaque clic publicitaire doit arriver au bon message",
      intro: [
        "Envoyer une campagne vers une page générique dilue l’intention. Une landing page reprend la promesse de l’annonce, répond aux objections essentielles et maintient l’utilisateur concentré sur une seule prochaine étape.",
        "Nous travaillons le message, la hiérarchie, les preuves et la performance technique ensemble. La mesure des événements permet ensuite de comprendre ce qui génère réellement des contacts et d’améliorer la page avec des données utiles.",
      ],
      benefits: [
        { title: "Message aligné", text: "La promesse de la publicité continue sur la page pour éviter la rupture et la confusion." },
        { title: "Moins de distractions", text: "Une structure courte, des objections traitées et un appel à l’action principal clairement répété." },
        { title: "Mesure exploitable", text: "Événements de conversion et paramètres de campagne préparés pour analyser la qualité des leads." },
      ],
      deliverables: ["Structure de conversion", "Copywriting de page", "Design responsive", "Développement de page", "Tracking GA4", "CTA formulaire ou WhatsApp"],
      process: [
        { title: "Offre & audience", text: "Nous clarifions la promesse, la source du trafic et l’action qui définit une conversion." },
        { title: "Message", text: "Accroche, bénéfices, preuves, objections et appels à l’action organisés dans le bon ordre." },
        { title: "Design & build", text: "Interface responsive et mobile-first, cohérente avec la campagne et votre marque." },
        { title: "Mesure", text: "Configuration des événements et lecture des premiers signaux pour guider les améliorations." },
      ],
      audiences: ["Campagnes Meta Ads", "Campagnes Google Ads", "Lancement d’une nouvelle offre", "Génération de rendez-vous ou leads"],
      faq: [
        { q: "Pourquoi ne pas utiliser la page d’accueil ?", a: "La page d’accueil présente toute l’entreprise. Une landing page répond à une intention précise et réduit les distractions, ce qui facilite la mesure et l’optimisation de la campagne." },
        { q: "Pouvez-vous rédiger le contenu ?", a: "Oui. Nous structurons le message à partir de votre offre, vos preuves et les questions de vos clients. Votre validation garantit que chaque promesse reste exacte." },
        { q: "La landing page fonctionne-t-elle avec Meta et Google Ads ?", a: "Oui. Elle peut être adaptée aux deux canaux, avec un message et un suivi cohérents selon la campagne et les paramètres utilisés." },
        { q: "Peut-on tester plusieurs versions ?", a: "La structure peut être préparée pour comparer des accroches, preuves ou appels à l’action. Un test utile nécessite toutefois assez de trafic et un objectif de conversion bien défini." },
      ],
    },
    en: {
      name: "Landing pages",
      metaTitle: "Landing Page Design in Casablanca | Morocco",
      metaTitleAbsolute: true,
      metaDescription: "Conversion-focused landing page design in Casablanca for Meta Ads and Google Ads, with responsive design, GA4 tracking, forms and WhatsApp CTAs.",
      eyebrow: "Landing pages · Casablanca and Morocco",
      title: "Landing Page Design in Casablanca",
      highlight: "One page focused on one offer, one audience and one action.",
      description: "We create conversion-focused landing pages for Casablanca businesses and campaigns across Morocco, turning campaign traffic into qualified enquiries, booked appointments or WhatsApp conversations.",
      introTitle: "Every ad click should arrive at the right message",
      intro: [
        "Sending a campaign to a generic page dilutes intent. A landing page carries the promise of the ad forward, answers the essential objections and keeps users focused on one next step.",
        "We work on the message, hierarchy, proof points and technical performance together. Event tracking then shows what is genuinely generating enquiries and helps improve the page with useful data.",
      ],
      benefits: [
        { title: "Aligned message", text: "The advertising promise continues on the page to avoid a disconnect or confusion." },
        { title: "Fewer distractions", text: "A concise structure, addressed objections and one clearly repeated primary call to action." },
        { title: "Actionable measurement", text: "Conversion events and campaign parameters prepared to analyse lead quality." },
      ],
      deliverables: ["Conversion structure", "Landing page copywriting", "Responsive design", "Landing page development", "GA4 tracking", "Form or WhatsApp CTA"],
      process: [
        { title: "Offer & audience", text: "We clarify the promise, traffic source and action that defines a conversion." },
        { title: "Message", text: "Headline, benefits, proof points, objections and calls to action arranged in the right order." },
        { title: "Design & build", text: "A responsive, mobile-first interface consistent with the campaign and your brand." },
        { title: "Measurement", text: "Event setup and review of early signals to guide improvements." },
      ],
      audiences: ["Meta Ads campaigns", "Google Ads campaigns", "Launching a new offer", "Generating appointments or leads"],
      faq: [
        { q: "Why not use the homepage?", a: "The homepage presents the whole business. A landing page answers a specific intent and reduces distractions, making the campaign easier to measure and optimise." },
        { q: "Can you write the content?", a: "Yes. We structure the message around your offer, proof points and customers’ questions. Your approval ensures that every promise remains accurate." },
        { q: "Does the landing page work with Meta and Google Ads?", a: "Yes. It can be adapted to both channels, with messaging and tracking consistent with the campaign and parameters used." },
        { q: "Can we test several versions?", a: "The structure can be prepared to compare headlines, proof points or calls to action. A useful test does, however, require sufficient traffic and a clearly defined conversion goal." },
      ],
    },
  },
  {
    slug: "ecommerce-maroc",
    icon: "ShoppingCart",
    related: ["creation-site-web-maroc", "backend-api", "maintenance-site-web"],
    fr: {
      name: "E-commerce",
      metaTitle: "Création site e-commerce Casablanca | Boutique en ligne au Maroc",
      metaTitleAbsolute: true,
      metaDescription: "Création de boutique en ligne à Casablanca : catalogue produits, paiement, livraison et gestion des commandes pour les entreprises au Maroc.",
      eyebrow: "E-commerce · Casablanca et Maroc",
      title: "Création de site e-commerce à Casablanca",
      highlight: "Une boutique simple à acheter, simple à gérer et prête à évoluer.",
      description: "Vous souhaitez vendre les produits de votre boutique sur Internet ou lancer une petite entreprise en ligne ? Nemsi Media conçoit des sites e-commerce pour les commerces de Casablanca et les entreprises au Maroc, autour de votre catalogue, de vos clients et de votre organisation.",
      introTitle: "Un site e-commerce pour les commerces de Casablanca et les entreprises au Maroc",
      intro: [
        "Pour un commerce physique qui passe en ligne, le premier enjeu est de présenter les produits et d’organiser les commandes. Le client doit pouvoir comprendre les tailles ou les variantes disponibles, consulter les frais de livraison et choisir son mode de paiement avant de confirmer son achat. Nous concevons ce parcours pour une utilisation sur mobile comme sur ordinateur.",
        "Pour une petite entreprise, le périmètre de départ peut se concentrer sur un catalogue limité, des fiches produit complètes et une gestion claire des commandes. La recherche avancée, les promotions ou les connexions à vos outils internes se décident selon vos besoins. L’objectif est de choisir les fonctionnalités que vous pourrez réellement exploiter au quotidien.",
        "La création de votre boutique commence par des décisions concrètes : qui met à jour le stock, quelles zones sont livrées, comment les frais sont calculés et comment les commandes sont confirmées. Nous définissons avec vous le catalogue, le paiement, la livraison et l’administration avant de choisir la solution technique.",
      ],
      portfolioProof: {
        title: "Des parcours e-commerce construits autour du catalogue et de la commande",
        text: "Pour Nature’s Dates, nous avons conçu une plateforme avec catalogue, pages produits, recettes et parcours distincts pour les particuliers et les professionnels. Pour Atelier Lamiaa, le catalogue détaillé et le panier facilitent la préparation des commandes.",
        linkLabel: "Voir les projets e-commerce",
      },
      benefits: [
        { title: "Achat sans friction", text: "Recherche, catégories, fiches produit, panier et commande hiérarchisés pour le mobile." },
        { title: "Gestion adaptée", text: "Catalogue, stock, commandes et contenus organisés selon le fonctionnement de votre équipe." },
        { title: "Base évolutive", text: "Architecture capable d’intégrer de nouveaux produits, paiements, transporteurs ou automatisations." },
      ],
      deliverables: ["Catalogue et catégories", "Fiches produit", "Panier et commande", "Paiement adapté", "Gestion des commandes", "Analytics e-commerce"],
      process: [
        { title: "Modèle commercial", text: "Produits, variantes, prix, stock, paiement, livraison et règles opérationnelles." },
        { title: "Parcours client", text: "Navigation, recherche, fiche produit, panier et étapes de commande sur mobile." },
        { title: "Intégrations", text: "Connexion des services nécessaires et préparation de l’administration quotidienne." },
        { title: "Tests & lancement", text: "Scénarios de commande, contrôles de performance, mesure et accompagnement de l’équipe." },
      ],
      audiences: ["Petites entreprises au Maroc", "Commerces locaux qui passent en ligne", "Marques qui vendent directement à leurs clients", "Boutiques en ligne à moderniser"],
      faq: [
        { q: "Quel site web choisir pour un commerce local au Maroc ?", a: "Un site vitrine convient pour présenter votre boutique, ses horaires et ses services, puis recevoir des demandes de contact. Un site e-commerce devient adapté si vos clients doivent consulter un catalogue, sélectionner des produits et passer commande en ligne. Le choix part de votre manière de vendre et de votre capacité à gérer les commandes." },
        { q: "Un site e-commerce convient-il à une petite entreprise ?", a: "Oui, si le périmètre correspond à votre activité. Commencez par les produits à vendre, leurs photos, leurs prix, le stock et les règles de livraison. Un petit catalogue bien renseigné peut constituer une première étape ; les fonctions supplémentaires doivent répondre à un besoin identifié, comme les variantes ou le suivi des commandes." },
        { q: "Quel budget prévoir pour créer un site e-commerce au Maroc ?", a: "Le devis dépend du nombre de produits et de variantes, du design, des contenus à préparer et des intégrations de paiement, de livraison ou de gestion. Précisez également les langues souhaitées et les données à reprendre d’un site existant. L’hébergement, les éventuels abonnements et la maintenance sont des postes à clarifier dans le devis pour comprendre le coût global." },
        { q: "Que préparer avant de demander un devis e-commerce ?", a: "Partagez la liste de vos produits, quelques exemples de fiches avec photos et prix, vos zones de livraison et les modes de paiement envisagés. Ajoutez votre identité visuelle, les langues du site, votre budget indicatif et la date souhaitée. Si vous avez déjà une boutique en ligne, indiquez son adresse et les difficultés que vous voulez résoudre." },
        { q: "Quelle plateforme e-commerce choisir au Maroc ?", a: "Le choix dépend du catalogue, des intégrations, du budget et de l’autonomie attendue. Nous comparons les solutions prêtes à l’emploi et le sur-mesure avant de recommander l’architecture la plus rationnelle." },
        { q: "Pouvez-vous intégrer le paiement en ligne ?", a: "Oui, selon l’éligibilité de votre entreprise et les prestataires disponibles. Le paiement à la livraison ou d’autres modes peuvent aussi être intégrés au parcours." },
        { q: "Comment gérer la livraison ?", a: "Nous structurons les zones, tarifs et méthodes de livraison selon vos partenaires. Des connexions plus avancées sont possibles lorsque le transporteur fournit les outils nécessaires." },
        { q: "Le site pourra-t-il évoluer ?", a: "Oui. Nous anticipons les variantes, promotions, contenus et intégrations prioritaires afin d’éviter une reconstruction quand l’activité grandit." },
      ],
    },
    en: {
      name: "E-commerce",
      metaTitle: "E-commerce website development in Casablanca | Morocco",
      metaTitleAbsolute: true,
      metaDescription: "E-commerce website development in Casablanca: product catalogue, payment, delivery and order management for businesses in Morocco.",
      eyebrow: "E-commerce · Casablanca and Morocco",
      title: "E-commerce website development in Casablanca",
      highlight: "An online shop that is easy to buy from, easy to manage and ready to grow.",
      description: "Would you like to sell your shop’s products online or launch a small online business? Nemsi Media develops e-commerce websites for shops in Casablanca and businesses across Morocco around your catalogue, customers and operations.",
      introTitle: "An e-commerce website for Casablanca shops and businesses across Morocco",
      intro: [
        "For a physical shop moving online, the first challenge is presenting products and organising orders. Customers need to understand available sizes or variants, review delivery charges and choose a payment method before confirming their purchase. We design this journey for mobile and desktop use alike.",
        "For a small business, the initial scope can focus on a limited catalogue, complete product pages and clear order management. Advanced search, promotions or connections to your internal tools are decided according to your needs. The goal is to choose functionality you can genuinely use every day.",
        "Creating your shop starts with concrete decisions: who updates stock, which areas you deliver to, how delivery charges are calculated and how orders are confirmed. Together, we define the catalogue, payment, delivery and administration before choosing the technical solution.",
      ],
      portfolioProof: {
        title: "E-commerce journeys built around catalogues and ordering",
        text: "For Nature’s Dates, we designed a platform with a catalogue, product pages, recipes and distinct journeys for individual and business customers. For Atelier Lamiaa, a detailed catalogue and basket make it easier to prepare orders.",
        linkLabel: "View e-commerce projects",
      },
      benefits: [
        { title: "Frictionless purchasing", text: "Search, categories, product pages, basket and checkout prioritised for mobile." },
        { title: "Operations that fit", text: "Catalogue, stock, orders and content organised around how your team works." },
        { title: "A scalable foundation", text: "An architecture that can integrate new products, payments, carriers or automations." },
      ],
      deliverables: ["Catalogue and categories", "Product pages", "Basket and checkout", "Suitable payment solution", "Order management", "E-commerce analytics"],
      process: [
        { title: "Business model", text: "Products, variants, prices, stock, payment, delivery and operating rules." },
        { title: "Customer journey", text: "Mobile navigation, search, product page, basket and checkout steps." },
        { title: "Integrations", text: "Connecting the required services and preparing day-to-day administration." },
        { title: "Testing & launch", text: "Order scenarios, performance checks, measurement and team support." },
      ],
      audiences: ["Small businesses in Morocco", "Local shops moving online", "Brands selling directly to customers", "Online shops that need modernising"],
      faq: [
        { q: "Which website should a local shop in Morocco choose?", a: "A brochure website is suitable for presenting your shop, opening hours and services, then receiving contact enquiries. An e-commerce website becomes appropriate if customers need to browse a catalogue, select products and order online. The choice starts with how you sell and your capacity to manage orders." },
        { q: "Is an e-commerce website suitable for a small business?", a: "Yes, if the scope matches your operations. Start with the products to sell, their photos, prices, stock and delivery rules. A well-documented small catalogue can be a first step; additional features should answer an identified need, such as variants or order tracking." },
        { q: "What budget should I plan for an e-commerce website in Morocco?", a: "The quote depends on the number of products and variants, design, content to prepare, and payment, delivery or management integrations. Also specify the desired languages and data to migrate from an existing website. Hosting, any subscriptions and maintenance should be clarified in the quote to understand the total cost." },
        { q: "What should I prepare before requesting an e-commerce quote?", a: "Share your product list, a few example product pages with photos and prices, your delivery areas and intended payment methods. Add your visual identity, the website languages, an indicative budget and desired date. If you already have an online shop, provide its address and the issues you want to solve." },
        { q: "Which e-commerce platform should I choose in Morocco?", a: "The choice depends on the catalogue, integrations, budget and the autonomy you expect. We compare ready-made and custom solutions before recommending the most rational architecture." },
        { q: "Can you integrate online payments?", a: "Yes, depending on your business’s eligibility and the providers available. Cash on delivery or other methods can also be integrated into the journey." },
        { q: "How is delivery managed?", a: "We structure delivery areas, rates and methods around your partners. More advanced connections are possible when the carrier provides the necessary tools." },
        { q: "Will the website be able to grow?", a: "Yes. We anticipate priority variants, promotions, content and integrations so you can avoid rebuilding when the business grows." },
      ],
    },
  },
  {
    slug: "seo-maroc",
    icon: "Search",
    related: ["creation-site-web-maroc", "ecommerce-maroc", "maintenance-site-web"],
    fr: {
      name: "SEO & visibilité",
      metaTitle: "Agence SEO Casablanca | Référencement naturel au Maroc",
      metaDescription: "Agence SEO à Casablanca : audit SEO technique, stratégie de contenu, optimisation et suivi Search Console pour les entreprises au Maroc.",
      eyebrow: "SEO · Casablanca et Maroc",
      title: "Agence SEO à Casablanca",
      highlight: "Construire une visibilité utile auprès des personnes qui cherchent déjà vos services.",
      description: "Nemsi Media accompagne les entreprises de Casablanca avec une stratégie SEO adaptée à leur activité, puis soutient les projets menés à l’échelle du Maroc. Nous identifions les recherches pertinentes, corrigeons les obstacles techniques et construisons un plan de contenu utile.",
      introTitle: "Une stratégie SEO pour les entreprises de Casablanca et du Maroc",
      intro: [
        "Être visible ne consiste pas à répéter des mots-clés. Une page doit répondre précisément à une question, démontrer l’expertise de l’entreprise et offrir une expérience technique solide sur mobile comme sur ordinateur.",
        "Notre travail combine audit, architecture, contenu, données structurées et mesure. Les priorités sont choisies selon la valeur commerciale, la concurrence et les ressources disponibles, sans promesse artificielle de première position.",
      ],
      resources: [
        { id: "seo-maroc-2026", title: "SEO au Maroc : les priorités 2026 pour gagner en visibilité", description: "Priorités éditoriales et techniques pour une visibilité durable." },
        { id: "seo-local-maroc", title: "SEO local au Maroc : Casablanca, Rabat, Marrakech", description: "Comprendre les enjeux de visibilité selon une zone de service." },
        { id: "performance-web-mobile-maroc", title: "Performance web : la vitesse, facteur clé de conversion", description: "Repères pour relier performance mobile et expérience de recherche." },
      ],
      benefits: [
        { title: "Priorités claires", text: "Un audit traduit en actions classées par impact, effort et lien avec vos objectifs commerciaux." },
        { title: "Contenu utile", text: "Pages services et contenus éditoriaux construits autour des questions et intentions réelles." },
        { title: "Mesure durable", text: "Suivi de l’indexation, des requêtes, des pages d’entrée et des conversions organiques." },
      ],
      deliverables: ["Audit SEO technique", "Recherche d’intentions", "Architecture éditoriale", "Optimisation on-page", "Données structurées", "Suivi Search Console"],
      process: [
        { title: "Diagnostic", text: "Exploration, indexation, performances, contenus, concurrence et mesure existante." },
        { title: "Stratégie", text: "Regroupement des intentions et priorisation des pages qui soutiennent le mieux l’activité." },
        { title: "Optimisation", text: "Corrections techniques, amélioration des pages et création des contenus manquants." },
        { title: "Apprentissage", text: "Lecture des données, mise à jour des priorités et amélioration continue des pages utiles." },
      ],
      audiences: ["Entreprises locales", "Services B2B", "E-commerce", "Sites qui génèrent peu de trafic qualifié"],
      faq: [
        { q: "Combien de temps faut-il pour obtenir des résultats SEO ?", a: "Le délai varie selon l’état du site, la concurrence, le contenu et l’autorité du domaine. Les corrections techniques peuvent être rapides, tandis que la croissance organique demande généralement un travail continu et des données suffisantes." },
        { q: "Pouvez-vous garantir la première position ?", a: "Non. Aucun prestataire sérieux ne contrôle l’algorithme ou les actions des concurrents. Nous garantissons une méthode transparente, des optimisations conformes et un suivi des indicateurs utiles." },
        { q: "Le SEO local est-il inclus ?", a: "La pertinence locale peut faire partie de la stratégie selon votre activité, l’intention de recherche, des contenus liés à votre zone de service et la cohérence des informations de l’entreprise." },
        { q: "Faut-il publier des articles ?", a: "Pas systématiquement. Nous privilégions d’abord les pages qui répondent à une intention commerciale. Les articles servent ensuite les questions importantes qui ne trouvent pas leur place dans une page service." },
      ],
    },
    en: {
      name: "SEO & Visibility",
      metaTitle: "SEO Agency in Casablanca | SEO Services in Morocco",
      metaDescription: "SEO agency in Casablanca: technical SEO audit, content strategy, optimisation and Search Console monitoring for businesses across Morocco.",
      eyebrow: "SEO · Casablanca and Morocco",
      title: "SEO Agency in Casablanca",
      highlight: "Build meaningful visibility among people already looking for your services.",
      description: "Nemsi Media supports Casablanca businesses with SEO strategies suited to their activity and projects across Morocco. We identify the searches that matter, remove technical barriers and build a useful content plan.",
      introTitle: "An SEO strategy for businesses in Casablanca and across Morocco",
      intro: [
        "Being visible is not about repeating keywords. A page needs to answer a question precisely, demonstrate the company’s expertise and deliver a sound technical experience on mobile and desktop.",
        "Our work combines auditing, architecture, content, structured data and measurement. We choose priorities based on commercial value, competition and available resources, without artificial promises of a number-one ranking.",
      ],
      resources: [
        { id: "seo-maroc-2026", title: "SEO in Morocco: 2026 priorities for gaining visibility", description: "Editorial and technical priorities for lasting visibility." },
        { id: "seo-local-maroc", title: "Local SEO in Morocco: Casablanca, Rabat, Marrakech", description: "Understanding visibility challenges around a service area." },
        { id: "performance-web-mobile-maroc", title: "Web performance: speed as a key conversion factor", description: "How mobile performance relates to the search experience." },
      ],
      benefits: [
        { title: "Clear priorities", text: "An audit translated into actions ranked by impact, effort and relevance to your commercial objectives." },
        { title: "Useful content", text: "Service pages and editorial content built around real questions and search intent." },
        { title: "Lasting measurement", text: "Tracking of indexing, search queries, entry pages and organic conversions." },
      ],
      deliverables: ["Technical SEO audit", "Search-intent research", "Content architecture", "On-page optimisation", "Structured data", "Search Console monitoring"],
      process: [
        { title: "Diagnosis", text: "Crawling, indexing, performance, content, competition and existing measurement." },
        { title: "Strategy", text: "Grouping search intents and prioritising the pages that best support the business." },
        { title: "Optimisation", text: "Technical fixes, page improvements and creation of missing content." },
        { title: "Learning", text: "Reviewing data, updating priorities and continuously improving the pages that matter." },
      ],
      audiences: ["Local businesses", "B2B services", "E-commerce", "Sites that generate little qualified traffic"],
      faq: [
        { q: "How long does it take to see SEO results?", a: "Timing varies with the site’s condition, competition, content and domain authority. Technical fixes can be quick, while organic growth usually requires ongoing work and enough data." },
        { q: "Can you guarantee a first-place ranking?", a: "No. No serious provider controls the algorithm or competitors’ actions. We guarantee a transparent method, compliant optimisation and tracking of useful indicators." },
        { q: "Is local SEO included?", a: "Local relevance can be part of the strategy depending on your activity, search intent, content related to your service area and consistent business information." },
        { q: "Do we need to publish articles?", a: "Not always. We first prioritise pages that address commercial intent. Articles then serve important questions that do not belong on a service page." },
      ],
    },
  },
  {
    slug: "maintenance-site-web",
    icon: "Wrench",
    related: ["creation-site-web-maroc", "seo-maroc", "backend-api"],
    fr: {
      name: "Maintenance",
      metaTitle: "Maintenance de site web à Casablanca | Maroc",
      metaTitleAbsolute: true,
      metaDescription: "Maintenance de site web à Casablanca : mises à jour, sécurité, sauvegardes, monitoring et corrections pour garder votre site fiable au Maroc.",
      eyebrow: "Maintenance web · Casablanca et Maroc",
      title: "Maintenance de site web à Casablanca",
      highlight: "Un site surveillé, mis à jour et prêt à accompagner votre activité.",
      description: "À Casablanca, nous assurons le suivi technique de votre site pour réduire les interruptions, corriger les problèmes, maintenir les dépendances et faire évoluer les fonctionnalités utiles.",
      introTitle: "La mise en ligne n’est pas la fin du projet",
      intro: [
        "Les navigateurs, bibliothèques, intégrations et besoins métier évoluent. Sans suivi, de petites anomalies peuvent devenir des problèmes de sécurité, de performance ou de conversion.",
        "À Casablanca, nous assurons le suivi technique des sites des entreprises marocaines : mises à jour, corrections, sauvegardes et contrôles, organisés selon la criticité du site et votre rythme d’évolution. Vous disposez d’un point de contact clair, d’un historique des interventions et d’une base plus prévisible pour les améliorations.",
      ],
      benefits: [
        { title: "Risque réduit", text: "Mises à jour suivies, contrôles essentiels et sauvegardes adaptées à l’architecture du projet." },
        { title: "Performance surveillée", text: "Détection des erreurs, liens cassés ou ralentissements avant qu’ils n’affectent durablement les visiteurs." },
        { title: "Évolutions cadrées", text: "Petites améliorations et nouvelles demandes priorisées selon leur impact réel." },
      ],
      deliverables: ["Mises à jour techniques", "Sauvegardes", "Monitoring", "Corrections de bugs", "Contrôles de sécurité", "Rapport d’intervention"],
      process: [
        { title: "Audit initial", text: "Technologies, hébergement, accès, dépendances, sauvegardes et problèmes connus." },
        { title: "Plan de suivi", text: "Fréquence, périmètre, priorités et méthode de remontée des demandes." },
        { title: "Maintenance", text: "Mises à jour contrôlées, vérifications, corrections et tests des parcours essentiels." },
        { title: "Amélioration", text: "Bilan régulier et recommandations selon les incidents, usages et objectifs du site." },
      ],
      audiences: ["Sites vitrines actifs", "Boutiques e-commerce", "Applications et outils métier existants", "Équipes sans ressource technique interne"],
      resources: [
        { id: "performance-web-mobile-maroc", title: "Performance web : la vitesse, facteur clé de conversion", description: "Repères pour relier performance mobile et expérience de recherche." },
      ],
      faq: [
        { q: "Que comprend un contrat de maintenance ?", a: "Le périmètre peut inclure mises à jour, sauvegardes, monitoring, corrections et temps d’évolution. Il est défini selon la technologie et la criticité de votre site." },
        { q: "Pouvez-vous maintenir un site que vous n’avez pas créé ?", a: "Oui, après un audit technique. Celui-ci permet de vérifier la qualité du code, les accès, la documentation et les risques avant de confirmer le périmètre." },
        { q: "La maintenance protège-t-elle contre toutes les attaques ?", a: "Aucun système ne garantit un risque nul. Une maintenance sérieuse réduit l’exposition grâce aux mises à jour, sauvegardes, contrôles et bonnes pratiques adaptées." },
        { q: "Mon site est lent. Pouvez-vous l’optimiser ?", a: "Oui. Nous commençons par mesurer pour identifier la cause, qu’il s’agisse de ressources trop lourdes, de scripts ou de requêtes. Les corrections techniques pertinentes sont ensuite priorisées, puis nous mesurons à nouveau." },
      ],
    },
    en: {
      name: "Maintenance",
      metaTitle: "Website Maintenance in Casablanca | Morocco",
      metaTitleAbsolute: true,
      metaDescription: "Website maintenance in Casablanca: updates, security, backups, monitoring and fixes to keep your site reliable across Morocco.",
      eyebrow: "Web maintenance · Casablanca and Morocco",
      title: "Website Maintenance in Casablanca",
      highlight: "A monitored, updated website ready to support your business.",
      description: "For businesses in Casablanca, we provide technical support for your site to reduce downtime, resolve issues, maintain dependencies and develop useful features.",
      introTitle: "Launching a website is not the end of the project",
      intro: [
        "Browsers, libraries, integrations and business needs evolve. Without ongoing support, minor issues can become security, performance or conversion problems.",
        "In Casablanca, we provide technical maintenance for businesses across Morocco: updates, fixes, backups and checks, organised around your site’s criticality and pace of change. You get a clear point of contact, a history of interventions and a more predictable foundation for improvements.",
      ],
      benefits: [
        { title: "Reduced risk", text: "Managed updates, essential checks and backups tailored to the project’s architecture." },
        { title: "Monitored performance", text: "Detection of errors, broken links and slowdowns before they have a lasting effect on visitors." },
        { title: "Structured improvements", text: "Small improvements and new requests prioritised according to their real impact." },
      ],
      deliverables: ["Technical updates", "Backups", "Monitoring", "Bug fixes", "Security checks", "Intervention report"],
      process: [
        { title: "Initial audit", text: "Technologies, hosting, access, dependencies, backups and known issues." },
        { title: "Support plan", text: "Frequency, scope, priorities and the process for submitting requests." },
        { title: "Maintenance", text: "Controlled updates, checks, fixes and testing of essential user journeys." },
        { title: "Improvement", text: "Regular reviews and recommendations based on incidents, usage and site objectives." },
      ],
      audiences: ["Active brochure websites", "E-commerce stores", "Existing business applications and internal tools", "Teams without an in-house technical resource"],
      resources: [
        { id: "performance-web-mobile-maroc", title: "Web performance: speed as a key conversion factor", description: "Pointers connecting mobile performance and search experience." },
      ],
      faq: [
        { q: "What does a maintenance contract include?", a: "The scope can include updates, backups, monitoring, fixes and development time. It is defined according to your site’s technology and criticality." },
        { q: "Can you maintain a website you did not build?", a: "Yes, following a technical audit. It lets us assess code quality, access, documentation and risks before confirming the scope." },
        { q: "Does maintenance protect against every attack?", a: "No system guarantees zero risk. Serious maintenance reduces exposure through updates, backups, checks and appropriate best practices." },
        { q: "My website is slow. Can you optimise it?", a: "Yes. We start by measuring to identify the cause, whether it is heavy assets, scripts or requests. The relevant technical fixes are then prioritised, and we measure again." },
      ],
    },
  },
  {
    slug: "application-web-sur-mesure",
    icon: "LayoutDashboard",
    related: ["backend-api", "ui-ux-identite-visuelle", "maintenance-site-web"],
    fr: {
      name: "Applications web",
      metaTitle: "Application web sur mesure à Casablanca | Maroc",
      metaTitleAbsolute: true,
      metaDescription: "Applications web sur mesure à Casablanca : outils métier, dashboards et portails clients pour centraliser les données, rôles et processus au Maroc.",
      eyebrow: "Applications web · Casablanca et Maroc",
      title: "Développement d’applications web sur mesure à Casablanca",
      highlight: "Un outil construit autour de vos processus, pas l’inverse.",
      description: "Nous développons des applications web sur mesure pour les entreprises de Casablanca et les projets menés au Maroc : dashboards, portails clients et outils métier qui structurent les données, les rôles et les processus.",
      introTitle: "Structurer un processus métier dans une application web",
      intro: [
        "À Casablanca comme dans le reste du Maroc, les feuilles de calcul dispersées, tâches répétitives et échanges manuels compliquent le travail des équipes. Une application web bien cadrée centralise les données et rend chaque rôle plus autonome.",
        "Nous commençons par le processus et les décisions importantes, puis construisons uniquement les fonctionnalités nécessaires. Cette approche réduit la complexité, accélère l’adoption et facilite les évolutions futures.",
      ],
      benefits: [
        { title: "Processus centralisés", text: "Données, statuts et actions regroupés dans une interface adaptée aux différents rôles." },
        { title: "Moins de tâches manuelles", text: "Automatisations ciblées pour réduire les doubles saisies et les étapes répétitives." },
        { title: "Décisions plus lisibles", text: "Tableaux de bord et filtres conçus autour des indicateurs réellement utilisés." },
      ],
      deliverables: ["Cadrage fonctionnel", "UX de l’application", "Authentification", "Dashboard", "Gestion des rôles", "Documentation"],
      process: [
        { title: "Découverte métier", text: "Acteurs, tâches, données, règles, irritants et décisions prioritaires." },
        { title: "Prototype", text: "Parcours et écrans essentiels validés avant d’investir dans le développement complet." },
        { title: "Construction progressive", text: "Fonctionnalités livrées par blocs testables avec des retours réguliers des utilisateurs." },
        { title: "Déploiement & adoption", text: "Tests, sécurité, mise en ligne, accompagnement et plan d’évolution." },
      ],
      audiences: ["Équipes opérationnelles", "Portails clients ou partenaires", "SaaS en phase de validation", "Entreprises qui veulent remplacer des processus manuels"],
      faq: [
        { q: "Quelle différence avec un site web classique ?", a: "Un site présente principalement de l’information. Une application permet aux utilisateurs de se connecter, manipuler des données et accomplir des tâches selon des règles métier." },
        { q: "Faut-il développer toutes les fonctionnalités dès le début ?", a: "Non. Nous recommandons un premier périmètre utile qui valide le processus, puis des évolutions guidées par les usages réels." },
        { q: "Pouvez-vous gérer plusieurs types d’utilisateurs ?", a: "Oui. Les rôles et permissions sont définis selon les responsabilités afin que chaque utilisateur accède uniquement aux informations et actions nécessaires." },
        { q: "Comment sont protégées les données ?", a: "La sécurité est traitée à plusieurs niveaux : authentification, permissions, validation, stockage et suivi. Les mesures exactes dépendent de la sensibilité et de l’architecture du projet." },
      ],
    },
    en: {
      name: "Web Applications",
      metaTitle: "Custom Web Application Development in Casablanca | Morocco",
      metaTitleAbsolute: true,
      metaDescription: "Custom web applications in Casablanca: business tools, dashboards and client portals that centralise data, roles and workflows across Morocco.",
      eyebrow: "Web applications · Casablanca and Morocco",
      title: "Custom Web Application Development in Casablanca",
      highlight: "A tool built around your processes, not the other way around.",
      description: "We develop custom web applications for Casablanca businesses and projects across Morocco: dashboards, client portals and business tools that structure data, roles and workflows.",
      introTitle: "Structure a business process in a web application",
      intro: [
        "In Casablanca and across Morocco, scattered spreadsheets, repetitive tasks and manual handovers make teams harder to coordinate. A well-scoped web application centralises data and gives each role more autonomy.",
        "We start with the process and the decisions that matter, then build only the necessary features. This approach reduces complexity, speeds adoption and makes future improvements easier.",
      ],
      benefits: [
        { title: "Centralised processes", text: "Data, statuses and actions brought together in an interface suited to different roles." },
        { title: "Less manual work", text: "Targeted automation that reduces duplicate entry and repetitive steps." },
        { title: "Clearer decisions", text: "Dashboards and filters designed around the metrics people actually use." },
      ],
      deliverables: ["Functional scoping", "Application UX", "Authentication", "Dashboard", "Role management", "Documentation"],
      process: [
        { title: "Business discovery", text: "Stakeholders, tasks, data, rules, pain points and priority decisions." },
        { title: "Prototype", text: "Key journeys and screens validated before investing in full development." },
        { title: "Incremental build", text: "Features delivered in testable blocks with regular feedback from users." },
        { title: "Deployment & adoption", text: "Testing, security, launch, onboarding and an evolution plan." },
      ],
      audiences: ["Operations teams", "Client or partner portals", "SaaS products in validation", "Businesses replacing manual processes"],
      faq: [
        { q: "How is this different from a standard website?", a: "A website mainly presents information. An application lets users log in, work with data and complete tasks according to business rules." },
        { q: "Do we need to build every feature from the start?", a: "No. We recommend a useful first scope that validates the process, then improvements guided by real usage." },
        { q: "Can you manage multiple user types?", a: "Yes. Roles and permissions are defined according to responsibilities so each user can access only the information and actions they need." },
        { q: "How is data protected?", a: "Security is addressed on several levels: authentication, permissions, validation, storage and monitoring. The exact measures depend on the project’s sensitivity and architecture." },
      ],
    },
  },
  {
    slug: "backend-api",
    icon: "Server",
    related: ["application-web-sur-mesure", "ecommerce-maroc", "maintenance-site-web"],
    fr: {
      name: "Backend & API",
      metaTitle: "Intégration & développement d’APIs à Casablanca | Maroc",
      metaTitleAbsolute: true,
      metaDescription: "Intégration et développement d’APIs à Casablanca : architecture, données, authentification et connexion de vos outils pour des applications fiables au Maroc.",
      eyebrow: "Backend & API · Casablanca et Maroc",
      title: "Intégration et développement d’APIs à Casablanca",
      highlight: "La couche serveur qui fiabilise vos données et fait dialoguer vos outils.",
      description: "Nous développons les APIs, l’architecture et les intégrations qui fonctionnent derrière vos sites, applications métier et expériences e-commerce : données cohérentes, accès contrôlés et systèmes connectés.",
      introTitle: "Le backend, c’est ce qui se passe derrière l’interface",
      intro: [
        "Quand plusieurs interfaces, utilisateurs ou services partagent les mêmes données, une architecture improvisée crée vite des incohérences. Le backend doit définir clairement les règles, les accès et les échanges entre vos outils.",
        "Basés à Casablanca, nous aidons les entreprises marocaines à structurer cette couche serveur : modèle de données, APIs, authentification et intégrations. La documentation et l’observabilité font partie du travail pour que la solution reste exploitable après la livraison.",
      ],
      benefits: [
        { title: "Données cohérentes", text: "Modèles, validations et règles métier centralisés pour limiter les erreurs entre systèmes." },
        { title: "Intégrations maîtrisées", text: "APIs internes ou externes connectées avec gestion des erreurs et suivi des échanges." },
        { title: "Évolution prévisible", text: "Architecture modulaire, documentation et tests ciblés pour faire grandir le produit." },
      ],
      deliverables: ["Architecture backend", "Modèle de données", "API REST", "Authentification", "Intégrations tierces", "Documentation technique"],
      process: [
        { title: "Contraintes & flux", text: "Sources de données, acteurs, volumes, sécurité, intégrations et disponibilité attendue." },
        { title: "Conception", text: "Modèles, endpoints, permissions, traitements et stratégie de gestion des erreurs." },
        { title: "Développement & tests", text: "Construction par modules, validations, tests des cas critiques et documentation." },
        { title: "Déploiement & suivi", text: "Environnements, logs, monitoring et procédure d’évolution ou d’incident." },
      ],
      audiences: ["Sites et applications à connecter", "Plateformes e-commerce", "Outils métier à faire dialoguer", "Produits qui dépassent les limites d’un backend existant"],
      faq: [
        { q: "Qu’est-ce qu’une API ?", a: "Une API définit comment plusieurs logiciels échangent des données et déclenchent des actions. Elle permet par exemple de relier un site, une application, un paiement ou un outil interne." },
        { q: "API sur mesure ou intégration d’une API existante ?", a: "Les deux répondent à des besoins différents. Une API sur mesure expose vos propres données à un autre système. L’intégration d’une API existante connecte un outil externe (paiement, CRM, messagerie) à votre produit. Un même projet mélange souvent les deux." },
        { q: "Mon application a-t-elle besoin d’un backend ?", a: "Dès que plusieurs interfaces ou utilisateurs partagent les mêmes données, que des règles métier s’appliquent ou qu’un outil externe doit être connecté, un backend devient nécessaire. À l’inverse, un site purement informatif peut s’en passer." },
        { q: "Comment préparez-vous la montée en charge ?", a: "Nous commençons par des mesures réalistes, une architecture modulaire, des requêtes efficaces et de l’observabilité. La complexité d’infrastructure n’est ajoutée que lorsqu’elle répond à un besoin mesuré." },
      ],
    },
    en: {
      name: "Backend & API",
      metaTitle: "API Development & Integration in Casablanca | Morocco",
      metaTitleAbsolute: true,
      metaDescription: "API development and integration in Casablanca: architecture, data, authentication and system connections for reliable applications across Morocco.",
      eyebrow: "Backend & API · Casablanca and Morocco",
      title: "API Development and Integration in Casablanca",
      highlight: "The server layer that keeps your data reliable and your tools talking.",
      description: "We develop the APIs, architecture and integrations that run behind your websites, business applications and e-commerce experiences: consistent data, controlled access and connected systems.",
      introTitle: "The backend is what happens behind the interface",
      intro: [
        "When several interfaces, users or services share the same data, improvised architecture quickly creates inconsistencies. The backend has to define the rules, access and exchanges between your tools clearly.",
        "Based in Casablanca, we help Moroccan businesses structure this server layer: data model, APIs, authentication and integrations. Documentation and observability are part of the work, so the solution stays practical to operate after delivery.",
      ],
      benefits: [
        { title: "Consistent data", text: "Centralised models, validation and business rules to limit errors between systems." },
        { title: "Controlled integrations", text: "Internal and external APIs connected with error handling and exchange monitoring." },
        { title: "Predictable evolution", text: "Modular architecture, documentation and targeted tests to help the product grow." },
      ],
      deliverables: ["Backend architecture", "Data model", "REST API", "Authentication", "Third-party integrations", "Technical documentation"],
      process: [
        { title: "Constraints & flows", text: "Data sources, stakeholders, volumes, security, integrations and expected availability." },
        { title: "Design", text: "Models, endpoints, permissions, processing and an error-management strategy." },
        { title: "Development & testing", text: "Modular development, validation, testing of critical cases and documentation." },
        { title: "Deployment & monitoring", text: "Environments, logs, monitoring and a process for changes or incidents." },
      ],
      audiences: ["Sites and applications to connect", "E-commerce platforms", "Business tools that need to talk", "Products outgrowing an existing backend"],
      faq: [
        { q: "What is an API?", a: "An API defines how software systems exchange data and trigger actions. It can connect a website, an application, a payment service or an internal tool, for example." },
        { q: "Custom API or integration of an existing one?", a: "They serve different needs. A custom API exposes your own data to another system. Integrating an existing API connects an external tool (payments, CRM, messaging) to your product. Most projects combine the two." },
        { q: "Does my application need a backend?", a: "As soon as several interfaces or users share the same data, business rules apply, or an external tool has to be connected, a backend becomes necessary. A purely informational website can do without one." },
        { q: "How do you prepare for growth in usage?", a: "We start with realistic measurements, modular architecture, efficient queries and observability. Infrastructure complexity is added only when it meets a measured need." },
      ],
    },
  },
]

export const serviceSlugs = serviceCatalog.map((service) => service.slug)

export function getServiceBySlug(slug) {
  return serviceCatalog.find((service) => service.slug === slug)
}
