import Link from "next/link"
import { ArrowUpRight } from "lucide-react"

const content = {
  fr: { title: "Avant de commencer.", intro: "Des réponses simples aux questions qui reviennent au début d’un projet.", cta: "Poser une autre question", questions: [["Quel budget prévoir pour un site ?", "Le budget dépend du périmètre, des contenus et des fonctions attendues. Nous commençons par cadrer le besoin, puis proposons un devis clair et détaillé."], ["Combien de temps faut-il ?", "Une landing page demande généralement moins de temps qu’un site corporate ou une boutique. Le calendrier est validé avant le démarrage et suivi étape par étape."], ["Le SEO est-il inclus ?", "Oui, les fondations techniques sont intégrées : structure, vitesse, mobile, métadonnées et indexation. Une stratégie éditoriale continue peut être ajoutée."], ["Pouvez-vous reprendre un site existant ?", "Oui. Nous auditons l’existant, conservons ce qui fonctionne et reconstruisons le design, la technique et le parcours sans perdre les acquis utiles."], ["Travaillez-vous hors Casablanca ?", "Oui. Nous collaborons avec des équipes partout au Maroc et à l’international avec un suivi simple et régulier."]] },
  en: { title: "Before we begin.", intro: "Straightforward answers to the questions that come up at the start of a project.", cta: "Ask another question", questions: [["What budget should I plan for a website?", "The budget depends on the scope, content and expected features. We first define the need, then provide a clear, detailed quote."], ["How long does it take?", "A landing page generally takes less time than a corporate website or online store. The timeline is agreed before the start and followed step by step."], ["Is SEO included?", "Yes, the technical foundations are included: structure, speed, mobile, metadata and indexing. An ongoing content strategy can be added."], ["Can you take over an existing website?", "Yes. We audit the current site, retain what works and rebuild the design, technology and user journey without losing useful assets."], ["Do you work outside Casablanca?", "Yes. We work with teams across Morocco and internationally through simple, regular follow-up."]] },
}

export function LeadFaq({ lang }) {
  const copy = content[lang] || content.fr
  return <section className="nm-faq section"><div className="container nm-faq__grid"><div><span className="nm-index">06</span><p className="nm-kicker">FAQ</p><h2>{copy.title}</h2><p>{copy.intro}</p><Link href={`/${lang}/contact`} className="nm-button nm-button--text">{copy.cta}<ArrowUpRight aria-hidden="true" /></Link></div><div>{copy.questions.map(([question, answer], index) => <details key={question} open={index === 0}><summary><span>0{index + 1}</span>{question}<i>+</i></summary><p>{answer}</p></details>)}</div></div></section>
}
