import Link from "next/link"
import { ArrowUpRight } from "lucide-react"
import Navbar from "./navbar"
import Footer from "./footer"
import { PageHero } from "./page-hero"

export function StudioPage({ lang }) {
  const isEnglish = lang === "en"
  const values = isEnglish ? [["01", "Clarity", "We remove the unnecessary so the message, interface, and decision become obvious."], ["02", "Precision", "We care for the system and small details that make an experience feel credible."], ["03", "Independence", "No copied formula. Every project starts from its real context."], ["04", "Continuity", "We build a foundation that can evolve, not just a beautiful one-off delivery."]] : [["01", "Clarté", "Nous retirons le superflu pour rendre le message, l’interface et la décision évidents."], ["02", "Précision", "Nous soignons le système et les petits détails qui rendent une expérience crédible."], ["03", "Indépendance", "Pas de recette copiée. Chaque projet part de son contexte réel."], ["04", "Continuité", "Nous construisons une base capable d’évoluer, pas seulement une belle livraison ponctuelle."]]
  const steps = isEnglish ? [["01", "Understand the context"], ["02", "Define the direction"], ["03", "Design and build"], ["04", "Launch and evolve"]] : [["01", "Comprendre le contexte"], ["02", "Définir la direction"], ["03", "Concevoir et construire"], ["04", "Lancer et faire évoluer"]]
  return <div><Navbar lang={lang} /><main><PageHero lang={lang} index="01" eyebrow={isEnglish ? "THE STUDIO" : "LE STUDIO"} title={isEnglish ? "Small team. Precise thinking. Real impact." : "Petite équipe. Pensée précise. Impact réel."} description={isEnglish ? "Nemsi Media is an independent digital studio in Casablanca. Strategy, design, and development brought together in one clear process." : "Nemsi Media est un studio digital indépendant à Casablanca. Stratégie, design et développement réunis dans un même processus lisible."} />
    <section className="nm-studio section"><div className="container"><div className="nm-studio__statement"><span className="nm-index">02</span><h2>{isEnglish ? "We design what the project needs, not what fills the screen." : "Nous dessinons ce dont le projet a besoin, pas ce qui remplit l’écran."}</h2></div><div className="nm-studio__values">{values.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="nm-process section"><div className="container"><div className="nm-section-heading"><span className="nm-index">03</span><p className="nm-kicker">{isEnglish ? "OUR METHOD" : "NOTRE MÉTHODE"}</p><h2>{isEnglish ? "A clear process, from framing to launch." : "Un processus lisible, du cadrage au lancement."}</h2></div><div className="nm-process__list">{steps.map(([number, title]) => <div key={number}><span>{number}</span><h3>{title}</h3><i>↘</i></div>)}</div><Link href={`/${lang}/contact`} className="nm-button nm-button--primary">{isEnglish ? "Let’s get to know each other" : "Faisons connaissance"}<ArrowUpRight /></Link></div></section>
  </main><Footer lang={lang} /></div>
}
