import { notFound } from "next/navigation"
import portfolioData from "../../lib/portfolio-data.json"
import { ProjectsIndex } from "../../components/projects-index"
import { OG_IMAGE, SITE_URL, SITE_NAME, seoKeywords } from "../../lib/seo"

const publicLocales = ["fr", "en"]
const isPublicLocale = (locale) => publicLocales.includes(locale)
const copy = {
  fr: { title: "Projets web, e-commerce et branding au Maroc", description: "Découvrez les sites web, boutiques e-commerce et expériences digitales réalisés par Nemsi Media pour des marques au Maroc.", keywords: ["portfolio agence web Maroc", "projets web Casablanca", "réalisations e-commerce Maroc"], alt: "Projets digitaux réalisés par Nemsi Media", inLanguage: "fr-MA", collection: "Réalisations digitales de Nemsi Media", home: "Accueil", label: "Projets" },
  en: { title: "Website, e-commerce and branding projects in Morocco", description: "Discover the websites, e-commerce stores and digital experiences created by Nemsi Media for brands in Morocco.", keywords: ["web agency portfolio Morocco", "web projects Casablanca", "e-commerce work Morocco"], alt: "Digital projects created by Nemsi Media", inLanguage: "en", collection: "Nemsi Media digital projects", home: "Home", label: "Projects" },
}
export const dynamicParams = false
export function generateStaticParams() { return publicLocales.map((locale) => ({ locale })) }
export async function generateMetadata({ params }) { const { locale } = await params; if (!isPublicLocale(locale)) return {}; const item = copy[locale]; const pageUrl = `${SITE_URL}/${locale}/projets`; return { title: item.title, description: item.description, keywords: [...seoKeywords, ...item.keywords], alternates: { canonical: pageUrl, languages: { "fr-MA": `${SITE_URL}/fr/projets`, en: `${SITE_URL}/en/projets`, "x-default": `${SITE_URL}/fr/projets` } }, openGraph: { title: item.title, description: item.description, url: pageUrl, siteName: SITE_NAME, locale: locale === "en" ? "en_US" : "fr_MA", alternateLocale: [locale === "en" ? "fr_MA" : "en_US"], type: "website", images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: item.alt }] }, twitter: { card: "summary_large_image", title: item.title, description: item.description, images: [OG_IMAGE] } } }
export default async function ProjectsPage({ params }) { const { locale } = await params; if (!isPublicLocale(locale)) notFound(); const item = copy[locale]; const pageUrl = `${SITE_URL}/${locale}/projets`; const projectsSchema = { "@context": "https://schema.org", "@graph": [{ "@type": "CollectionPage", "@id": `${pageUrl}#webpage`, url: pageUrl, name: item.title, description: item.description, inLanguage: item.inLanguage, isPartOf: { "@id": `${SITE_URL}/#website` }, about: { "@id": `${SITE_URL}/#organization` }, mainEntity: { "@id": `${pageUrl}#projects` } }, { "@type": "ItemList", "@id": `${pageUrl}#projects`, name: item.collection, numberOfItems: portfolioData.length, itemListElement: portfolioData.map((project, index) => ({ "@type": "ListItem", position: index + 1, item: { "@type": "CreativeWork", name: project.title[locale] || project.title.fr, description: project.challenge[locale] || project.challenge.fr, image: `${SITE_URL}${project.image}`, ...(project.liveUrl ? { url: project.liveUrl } : {}), creator: { "@id": `${SITE_URL}/#organization` } } })) }, { "@type": "BreadcrumbList", "@id": `${pageUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: item.home, item: `${SITE_URL}/${locale}` }, { "@type": "ListItem", position: 2, name: item.label, item: pageUrl }] }] }; return <><ProjectsIndex lang={locale} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(projectsSchema) }} /></> }
