export const branding = {
  slug: "branding-identite-marque",
  icon: "PenTool",
  related: ["ui-ux-identite-visuelle", "design-graphique-maroc", "social-media-maroc"],
  fr: {
    name: "Branding & identité",
    metaTitle: "Logo et identité de marque au Maroc",
    metaDescription: "Création de logo et identité de marque au Maroc : logo design, charte graphique, couleurs et typographie pour une marque mémorable et cohérente.",
    eyebrow: "Branding · Identité de marque",
    title: "Création de logo et identité de marque au Maroc",
    highlight: "Une identité visuelle forte qui rend votre marque mémorable.",
    description: "Nous concevons des identités de marque complètes : logo, palette, typographie et déclinaisons pour que votre entreprise soit reconnaissable et cohérente sur tous les supports.",
    introTitle: "Une marque qui se reconnaît et se retient",
    intro: [
      "Votre identité visuelle est la première impression que vous laissez. Elle doit traduire votre positionnement, inspirer confiance et rester reconnaissable sur un site, une carte de visite ou un réseau social.",
      "Nous construisons un système de marque cohérent : logo et déclinaisons, couleurs, typographies et règles d’usage que vous pourrez appliquer partout, aujourd’hui et demain.",
    ],
    benefits: [
      { title: "Reconnaissance immédiate", text: "Un logo et des codes visuels cohérents qui rendent votre marque identifiable au premier coup d’œil." },
      { title: "Cohérence sur tous les supports", text: "Règles, couleurs et typographies appliquées partout : site, réseaux sociaux, print et packaging." },
      { title: "Positionnement clair", text: "Une identité qui reflète votre valeur et votre public cible, pensée pour inspirer confiance." },
    ],
    deliverables: ["Logo principal", "Déclinaisons du logo", "Palette de couleurs", "Typographies", "Charte graphique", "Moodboard & direction artistique"],
    process: [
      { title: "Découverte", text: "Objectifs, positionnement, public cible, concurrence et références qui vous inspirent." },
      { title: "Concepts", text: "Plusieurs directions visuelles et pistes de logo présentées et testées." },
      { title: "Déclinaison", text: "Finalisation du logo, palette, typographies et variantes pour tous les supports." },
      { title: "Charte & livraison", text: "Règles d’usage et fichiers organisés pour une application cohérente par votre équipe." },
    ],
    audiences: ["Startups et nouvelles marques", "Entreprises en repositionnement", "Créateurs et indépendants", "Marques qui veulent s’internationaliser"],
    faq: [
      { q: "Quelle est la différence entre un logo et une identité de marque ?", a: "Le logo est un symbole d’identification. L’identité de marque regroupe le logo, ses déclinaisons, la palette, les typographies et les règles d’usage qui garantissent la cohérence sur tous les supports." },
      { q: "Combien de temps dure un projet de branding ?", a: "Cela dépend du périmètre. Un logo peut être livré en quelques semaines ; une identité complète avec charte demande généralement un accompagnement plus structuré pour garantir la cohérence." },
      { q: "Recevons-nous tous les fichiers ?", a: "Oui. Vous recevez les fichiers sources et optimisés (vecteurs, web, imprimables) ainsi qu’une charte pour appliquer correctement votre identité." },
      { q: "Pouvez-vous décliner notre identité sur les réseaux sociaux ?", a: "Oui. Nous adaptons votre logo et vos visuels aux dimensions et formats de chaque plateforme pour garder une image cohérente." },
    ],
  },
  en: {
    name: "Branding & identity",
    metaTitle: "Logo and brand identity in Morocco",
    metaDescription: "Logo and brand identity creation in Morocco: logo design, brand guidelines, colours and typography for a memorable, consistent brand.",
    eyebrow: "Branding · Brand identity",
    title: "Logo and brand identity creation in Morocco",
    highlight: "A strong visual identity that makes your brand memorable.",
    description: "We design complete brand identities: logo, colour palette, typography and applications so your business is recognisable and consistent across every touchpoint.",
    introTitle: "A brand people recognise and remember",
    intro: [
      "Your visual identity is the first impression you make. It should express your positioning, inspire trust and remain recognisable on a website, business card or social media channel.",
      "We build a consistent brand system: logo and variations, colours, typography and usage guidelines you can apply everywhere, today and tomorrow.",
    ],
    benefits: [
      { title: "Instant recognition", text: "A logo and consistent visual codes that make your brand identifiable at first glance." },
      { title: "Consistency across every touchpoint", text: "Guidelines, colours and typography applied everywhere: website, social media, print and packaging." },
      { title: "Clear positioning", text: "An identity that reflects your value and target audience, designed to inspire trust." },
    ],
    deliverables: ["Primary logo", "Logo variations", "Colour palette", "Typography", "Brand guidelines", "Moodboard & art direction"],
    process: [
      { title: "Discovery", text: "Goals, positioning, target audience, competitors and references that inspire you." },
      { title: "Concepts", text: "Several visual directions and logo concepts presented and tested." },
      { title: "Development", text: "Finalising the logo, palette, typography and variations for every touchpoint." },
      { title: "Guidelines & delivery", text: "Usage rules and organised files for consistent implementation by your team." },
    ],
    audiences: ["Startups and new brands", "Businesses repositioning themselves", "Creators and independents", "Brands looking to expand internationally"],
    faq: [
      { q: "What is the difference between a logo and a brand identity?", a: "A logo is an identifying symbol. A brand identity includes the logo, its variations, the palette, typography and usage guidelines that ensure consistency across every touchpoint." },
      { q: "How long does a branding project take?", a: "It depends on the scope. A logo can be delivered in a few weeks; a complete identity with guidelines generally requires a more structured engagement to ensure consistency." },
      { q: "Will we receive all the files?", a: "Yes. You receive source and optimised files (vector, web and print) along with guidelines to apply your identity correctly." },
      { q: "Can you adapt our identity for social media?", a: "Yes. We adapt your logo and visuals to the dimensions and formats of each platform to maintain a consistent image." },
    ],
  },
}
