export const branding = {
  slug: "branding-identite-marque",
  icon: "PenTool",
  related: ["ui-ux-identite-visuelle", "design-graphique-maroc", "social-media-maroc"],
  fr: {
    name: "Branding & identité",
    metaTitle: "Création de logo et identité de marque au Maroc",
    metaDescription: "Création de logo et identité de marque au Maroc : logo design, charte graphique, couleurs et typographie pour une marque mémorable et cohérente.",
    eyebrow: "Branding · Identité de marque",
    title: "Création de logo et identité de marque au Maroc",
    highlight: "Une identité visuelle forte qui rend votre marque mémorable.",
    description: "Nous concevons des identités de marque complètes : logo, palette, typographie et déclinaisons pour que votre entreprise soit reconnaissable et cohérente sur tous les supports.",
    introTitle: "Une marque qui se reconnaît et se retient",
    intro: [
      "Votre identité visuelle est la première impression que vous laissez. Elle doit traduire votre positionnement, inspirer confiance et rester reconnaissable sur un site, une carte de visite ou un réseau social.",
      "Nous construisons un système de marque cohérent : logo et déclinaisons, couleurs, typographies et règles d’usage que vous pourrez appliquer partout, aujourd’hui et demain.",
    ],
    benefits: [
      { title: "Reconnaissance immédiate", text: "Un logo et des codes visuels cohérents qui rendent votre marque identifiable au premier coup d’œil." },
      { title: "Cohérence sur tous les supports", text: "Règles, couleurs et typographies appliquées partout : site, réseaux sociaux, print et packaging." },
      { title: "Positionnement clair", text: "Une identité qui reflète votre valeur et votre public cible, pensée pour inspirer confiance." },
    ],
    deliverables: ["Logo principal", "Déclinaisons du logo", "Palette de couleurs", "Typographies", "Charte graphique", "Moodboard & direction artistique"],
    process: [
      { title: "Découverte", text: "Objectifs, positionnement, public cible, concurrence et références qui vous inspirent." },
      { title: "Concepts", text: "Plusieurs directions visuelles et pistes de logo présentées et testées." },
      { title: "Déclinaison", text: "Finalisation du logo, palette, typographies et variantes pour tous les supports." },
      { title: "Charte & livraison", text: "Règles d’usage et fichiers organisés pour une application cohérente par votre équipe." },
    ],
    audiences: ["Startups et nouvelles marques", "Entreprises en repositionnement", "Créateurs et indépendants", "Marques qui veulent s’internationaliser"],
    faq: [
      { q: "Quelle est la différence entre un logo et une identité de marque ?", a: "Le logo est un symbole d’identification. L’identité de marque regroupe le logo, ses déclinaisons, la palette, les typographies et les règles d’usage qui garantissent la cohérence sur tous les supports." },
      { q: "Combien de temps dure un projet de branding ?", a: "Cela dépend du périmètre. Un logo peut être livré en quelques semaines ; une identité complète avec charte demande généralement un accompagnement plus structuré pour garantir la cohérence." },
      { q: "Recevons-nous tous les fichiers ?", a: "Oui. Vous recevez les fichiers sources et optimisés (vecteurs, web, imprimables) ainsi qu’une charte pour appliquer correctement votre identité." },
      { q: "Pouvez-vous décliner notre identité sur les réseaux sociaux ?", a: "Oui. Nous adaptons votre logo et vos visuels aux dimensions et formats de chaque plateforme pour garder une image cohérente." },
    ],
  },
  ar: {
    name: "الهوية والعلامة التجارية",
    metaTitle: "تصميم شعار وهوية علامة تجارية في المغرب",
    metaDescription: "تصميم شعار وهوية علامة تجارية في المغرب: تصميم اللوغو ودليل الهوية والألوان والخطوط لعلامة مميزة ومتناسقة.",
    eyebrow: "الهوية والعلامة · تصميم الشعارات",
    title: "تصميم شعار وهوية علامة تجارية في المغرب",
    highlight: "هوية بصرية قوية تجعل علامتك لا تُنسى.",
    description: "نصمم هويات علامات تجارية متكاملة: الشعار والألوان والخطوط والدليل، ليكون مشروعك مميزاً ومتناسقاً على جميع المنصات.",
    introTitle: "علامة تُرى وتُتذكر",
    intro: [
      "الهوية البصرية هي الانطباع الأول الذي تتركه. يجب أن تعكس موقعك من السوق وتبني الثقة وتبقى مميزة على الموقع أو بطاقة العمل أو شبكات التواصل.",
      "نبني نظاماً متناسقاً للعلامة: الشعار وتفريعاته، الألوان والخطوط وقواعد الاستخدام التي يمكن تطبيقها في كل مكان اليوم وغداً.",
    ],
    benefits: [
      { title: "تميّز فوري", text: "شعار ورموز بصرية متناسقة تجعل علامتك واضحة من النظرة الأولى." },
      { title: "تناسق في كل مكان", text: "قواعد وألوان وخطوط مطبقة على الموقع وشبكات التواصل والمطبوعات والتغليف." },
      { title: "توجه واضح", text: "هوية تعكس قيمتك وجمهورك المستهدف، مصممة لبناء الثقة." },
    ],
    deliverables: ["الشعار الرئيسي", "تفريعات الشعار", "لوحة الألوان", "الخطوط", "دليل الهوية", "التوجه الفني والمزاج البصري"],
    process: [
      { title: "الاستكشاف", text: "نحدد الأهداف والتوجه والجمهور والمنافسين والمراجع الملهمة." },
      { title: "المفاهيم", text: "نقدم عدة توجهات بصرية وأفكاراً للشعار للاختبار والاختيار." },
      { title: "التفريع", text: "ننهي الشعار والألوان والخطوط والتنويعات لكل المنصات." },
      { title: "الدليل والتسليم", text: "نقدم قواعد الاستخدام والملفات المنظمة لتطبيق متناسق من فريقك." },
    ],
    audiences: ["الشركات الناشئة والعلامات الجديدة", "الشركات التي تعيد تموقعها", "المبدعون والمستقلون", "العلامات التي تتوسع دولياً"],
    faq: [
      { q: "ما الفرق بين الشعار وهوية العلامة؟", a: "الشعار رمز للتعريف، أما هوية العلامة فتشمل الشعار وتفريعاته والألوان والخطوط وقواعد الاستخدام لضمان التناسق على جميع المنصات." },
      { q: "كم تستغرق مدة مشروع الهوية؟", a: "يعتمد على النطاق. يمكن تسليم شعار خلال أسابيع، بينما تتطلب الهوية الكاملة مع الدليل مدة أطول لضمان التناسق." },
      { q: "هل نحصل على جميع الملفات؟", a: "نعم. نقدم الملفات المصدرية والمحسّنة (متجهات وويب وطباعة) مع دليل هوية لتطبيق صحيح." },
      { q: "هل يمكن تفعيل الهوية على شبكات التواصل؟", a: "نعم. نكيّف الشعار والتصاميم مع مقاسات كل منصة للحفاظ على صورة متناسقة." },
    ],
  },
}
