export const branding = {
  slug: "branding-identite-marque",
  icon: "PenTool",
  related: ["ui-ux-identite-visuelle", "design-graphique-maroc", "creation-site-web-maroc"],
  fr: {
    name: "Branding & identité",
    metaTitle: "Création d’identité visuelle à Casablanca | Logo & charte",
    metaTitleAbsolute: true,
    metaDescription: "Création d’identité visuelle à Casablanca : logo, palette, typographies et charte graphique pour une image cohérente au Maroc.",
    eyebrow: "Identité visuelle · Casablanca & Maroc",
    title: "Création d’identité visuelle à Casablanca",
    highlight: "Une identité visuelle structurée et cohérente.",
    description: "À Casablanca, nous créons des systèmes d’identité visuelle pour les entreprises au Maroc : logo, déclinaisons, palette, typographies et règles d’usage. Un logo est une partie de l’identité ; l’ensemble fournit des repères visuels réutilisables.",
    introTitle: "Donner un cadre visuel à votre marque",
    intro: [
      "Une identité visuelle définit comment utiliser un logo, ses déclinaisons, les couleurs et les typographies de manière cohérente. Elle pose une direction visuelle et des règles simples pour les usages à venir.",
      "Pour une création ou une identité existante à faire évoluer, nous clarifions les éléments visuels utiles et les organisons dans un système de marque. Cette base peut ensuite guider les applications graphiques ou le design d’interfaces digitales.",
    ],
    benefits: [
      { title: "Fondations visuelles claires", text: "Logo, couleurs et typographies réunis pour poser une base visuelle définie." },
      { title: "Règles réutilisables", text: "Des règles d’usage qui aident à appliquer les mêmes repères visuels dans les futurs besoins." },
      { title: "Système documenté", text: "Une charte qui rassemble les éléments de l’identité et leur utilisation." },
    ],
    deliverables: ["Logo principal", "Déclinaisons du logo", "Palette de couleurs", "Typographies", "Charte graphique", "Moodboard & direction artistique"],
    process: [
      { title: "Cadrage", text: "Projet, identité existante, contexte visuel et besoins à prendre en compte." },
      { title: "Directions visuelles", text: "Pistes de logo et directions visuelles pour définir le système à développer." },
      { title: "Développement du système", text: "Finalisation du logo, de la palette, des typographies et de leurs déclinaisons." },
      { title: "Charte & livraison", text: "Règles d’usage et fichiers organisés pour appliquer l’identité visuelle." },
    ],
    audiences: ["Nouvelles entreprises qui posent leurs fondations visuelles", "Entreprises qui font évoluer une identité existante", "Créateurs et indépendants", "Équipes qui préparent de futures applications digitales ou graphiques"],
    faq: [
      { q: "Quelle est la différence entre un logo et une identité visuelle ?", a: "Le logo est un élément de l’identité visuelle. Une identité complète rassemble le logo, ses déclinaisons, la palette, les typographies et les règles d’usage qui organisent le système visuel." },
      { q: "Que comprend une identité visuelle ?", a: "Selon le périmètre, elle comprend un logo principal, ses déclinaisons, une palette de couleurs, des typographies, une charte graphique, un moodboard et une direction artistique." },
      { q: "Pouvez-vous faire évoluer une identité existante ?", a: "Oui. Nous pouvons examiner les éléments existants, clarifier ceux à conserver et les organiser ou les faire évoluer dans un système visuel plus cohérent lorsque le projet le demande." },
      { q: "Quelle est la différence entre identité visuelle et design graphique ?", a: "L’identité visuelle définit les règles du système de marque : logo, couleurs, typographies et usages. Le design graphique applique ensuite ces règles à des supports de communication comme les visuels, flyers, posters ou bannières." },
    ],
    resources: [
      { id: "branding-identite-maroc", title: "Branding au Maroc : comment construire une marque mémorable", description: "Logo, palette, typographie et charte graphique : les éléments clés d’une identité de marque cohérente." },
    ],
  },
  en: {
    name: "Branding & identity",
    metaTitle: "Brand Identity Design in Casablanca | Logo & Guidelines",
    metaTitleAbsolute: true,
    metaDescription: "Brand identity design in Casablanca: logo, colour palette, typography and brand guidelines for a consistent presence across Morocco.",
    eyebrow: "Brand identity · Casablanca & Morocco",
    title: "Brand Identity Design in Casablanca",
    highlight: "A structured and consistent visual identity.",
    description: "In Casablanca, we create visual identity systems for businesses across Morocco: logo, variations, colour palette, typography and usage rules. A logo is one part of an identity; the full system provides reusable visual references.",
    introTitle: "Give your brand a visual framework",
    intro: [
      "A visual identity defines how to use a logo, its variations, colours and typography consistently. It establishes a visual direction and simple rules for future uses.",
      "For a new identity or an existing one that needs to evolve, we clarify the useful visual elements and organise them into a brand system. This foundation can later guide graphic applications or digital interface design.",
    ],
    benefits: [
      { title: "Clear visual foundations", text: "Logo, colours and typography brought together to establish a defined visual base." },
      { title: "Reusable rules", text: "Usage rules that help apply the same visual references to future needs." },
      { title: "A documented system", text: "Guidelines that bring together identity elements and how to use them." },
    ],
    deliverables: ["Primary logo", "Logo variations", "Colour palette", "Typography", "Brand guidelines", "Moodboard & art direction"],
    process: [
      { title: "Scoping", text: "The project, existing identity, visual context and needs to take into account." },
      { title: "Visual directions", text: "Logo options and visual directions to define the system to develop." },
      { title: "System development", text: "Finalising the logo, colour palette, typography and their variations." },
      { title: "Guidelines & delivery", text: "Usage rules and organised files for applying the visual identity." },
    ],
    audiences: ["New businesses establishing visual foundations", "Businesses evolving an existing identity", "Creators and independents", "Teams preparing future digital or graphic applications"],
    faq: [
      { q: "What is the difference between a logo and a visual identity?", a: "A logo is one element of a visual identity. A complete identity brings together the logo, its variations, colour palette, typography and usage rules that organise the visual system." },
      { q: "What does a visual identity include?", a: "Depending on the scope, it includes a primary logo, logo variations, a colour palette, typography, brand guidelines, a moodboard and art direction." },
      { q: "Can you evolve an existing identity?", a: "Yes. We can review existing elements, clarify which ones to retain and organise or evolve them into a more consistent visual system when the project calls for it." },
      { q: "What is the difference between visual identity and graphic design?", a: "Visual identity defines the brand-system rules: logo, colours, typography and usage. Graphic design then applies those rules to communication assets such as visuals, flyers, posters or banners." },
    ],
    resources: [
      { id: "branding-identite-maroc", title: "Branding in Morocco: how to build a memorable brand", description: "Logo, colour palette, typography and brand guidelines: the key elements of a consistent brand identity." },
    ],
  },
}
