export const photoVideo = {
  slug: "production-photo-video-maroc",
  icon: "Clapperboard",
  related: ["design-graphique-maroc", "social-media-maroc", "marketing-influence-maroc"],
  fr: {
    name: "Production photo & vidéo",
    metaTitle: "Production photo et vidéo au Maroc",
    metaDescription: "Production photo et vidéo au Maroc : photographie, vidéographie, montage et motion design pour des contenus visuels professionnels et impactants.",
    eyebrow: "Photo & vidéo · Production visuelle",
    title: "Production photo et vidéo professionnelle au Maroc",
    highlight: "Des visuels qui donnent vie à votre marque et captivent votre audience.",
    description: "Nous produisons photos, vidéos et motion design pour vos campagnes, réseaux sociaux et supports de communication, avec une direction artistique cohérente.",
    introTitle: "La vidéo est le langage le plus engageant",
    intro: [
      "Une photo bien cadrée ou une vidéo bien montée communique plus vite qu’un long texte. Nous transformons vos produits, services et valeurs en contenus visuels prêts à diffuser.",
      "De la captation à la post-production, nous assurons photographie, vidéographie, montage et motion design avec une ligne artistique alignée sur votre marque.",
    ],
    benefits: [
      { title: "Contenus engageants", text: "Des visuels conçus pour capter l’attention et générer des interactions sur vos canaux." },
      { title: "Direction artistique", text: "Une cohérence visuelle respectueuse de votre identité sur chaque format produit." },
      { title: "De la captation au montage", text: "Une équipe qui gère tournage, photographie, montage et motion design de bout en bout." },
    ],
    deliverables: ["Photographie produit", "Vidéos publicitaires", "Montage vidéo", "Motion design", "Séquences pour réseaux sociaux", "Sous-titrage et formats adaptés"],
    process: [
      { title: "Brief créatif", text: "Objectif, message, support de diffusion et direction artistique souhaitée." },
      { title: "Préparation", text: "Storyboard, lieux, casting et planning du tournage ou de la séance." },
      { title: "Captation", text: "Tournage photo ou vidéo professionnel selon le plan établi." },
      { title: "Post-production", text: "Montage, étalonnage, motion design et livraison aux formats requis." },
    ],
    audiences: ["Marques et commerces", "Campagnes publicitaires", "Réseaux sociaux et influence", "Événements et lancements produits"],
    faq: [
      { q: "Quels formats livrez-vous ?", a: "Vidéos verticales et horizontales, spots, photos haute résolution et déclinaisons pour chaque plateforme, selon l’usage prévu." },
      { q: "Gérez-vous le tournage sur place ?", a: "Oui. Nous assurons le repérage, le matériel, la direction et la captation sur site ou en studio selon votre besoin." },
      { q: "Pouvez-vous créer des vidéos animées ?", a: "Oui. Le motion design permet d’animer des logos, infographies et messages pour les formats web et publicitaires." },
      { q: "Combien de temps pour une vidéo ?", a: "Cela dépend de la complexité, du tournage et de la post-production. Nous établissons un délai clair avant le lancement." },
    ],
  },
  en: {
    name: "Photo & video production",
    metaTitle: "Photo and video production in Morocco",
    metaDescription: "Photo and video production in Morocco: photography, videography, editing and motion design for professional, impactful visual content.",
    eyebrow: "Photo & video · Visual production",
    title: "Professional photo and video production in Morocco",
    highlight: "Visual content that brings your brand to life and captivates your audience.",
    description: "We produce photography, video and motion design for your campaigns, social media and communication materials, with consistent art direction.",
    introTitle: "Video is the most engaging language",
    intro: [
      "A well-framed photo or well-edited video communicates faster than a long text. We turn your products, services and values into visual content ready to distribute.",
      "From filming to post-production, we handle photography, videography, editing and motion design with an artistic direction aligned with your brand.",
    ],
    benefits: [
      { title: "Engaging content", text: "Visual content designed to capture attention and generate interactions across your channels." },
      { title: "Art direction", text: "Visual consistency that respects your identity in every format produced." },
      { title: "From filming to editing", text: "A team that manages filming, photography, editing and motion design from start to finish." },
    ],
    deliverables: ["Product photography", "Advertising videos", "Video editing", "Motion design", "Social media clips", "Subtitles and adapted formats"],
    process: [
      { title: "Creative brief", text: "Objective, message, distribution channel and desired art direction." },
      { title: "Preparation", text: "Storyboard, locations, casting and schedule for the shoot or session." },
      { title: "Production", text: "Professional photo or video shoot based on the agreed plan." },
      { title: "Post-production", text: "Editing, colour grading, motion design and delivery in the required formats." },
    ],
    audiences: ["Brands and retailers", "Advertising campaigns", "Social media and influencer marketing", "Events and product launches"],
    faq: [
      { q: "Which formats do you deliver?", a: "Vertical and horizontal videos, spots, high-resolution photos and adaptations for each platform, according to the intended use." },
      { q: "Do you manage on-site shoots?", a: "Yes. We handle scouting, equipment, direction and filming on location or in a studio according to your needs." },
      { q: "Can you create animated videos?", a: "Yes. Motion design can animate logos, infographics and messages for web and advertising formats." },
      { q: "How long does a video take?", a: "It depends on the complexity, filming and post-production. We establish a clear timeline before launch." },
    ],
  },
}
