export const photoVideo = {
  slug: "production-photo-video-maroc",
  icon: "Clapperboard",
  related: ["design-graphique-maroc", "social-media-maroc", "marketing-influence-maroc"],
  fr: {
    name: "Production photo & vidéo",
    metaTitle: "Production photo et vidéo au Maroc",
    metaDescription: "Production photo et vidéo au Maroc : photographie, vidéographie, montage et motion design pour des contenus visuels professionnels et impactants.",
    eyebrow: "Photo & vidéo · Production visuelle",
    title: "Production photo et vidéo professionnelle au Maroc",
    highlight: "Des visuels qui donnent vie à votre marque et captivent votre audience.",
    description: "Nous produisons photos, vidéos et motion design pour vos campagnes, réseaux sociaux et supports de communication, avec une direction artistique cohérente.",
    introTitle: "La vidéo est le langage le plus engageant",
    intro: [
      "Une photo bien cadrée ou une vidéo bien montée communique plus vite qu’un long texte. Nous transformons vos produits, services et valeurs en contenus visuels prêts à diffuser.",
      "De la captation à la post-production, nous assurons photographie, vidéographie, montage et motion design avec une ligne artistique alignée sur votre marque.",
    ],
    benefits: [
      { title: "Contenus engageants", text: "Des visuels conçus pour capter l’attention et générer des interactions sur vos canaux." },
      { title: "Direction artistique", text: "Une cohérence visuelle respectueuse de votre identité sur chaque format produit." },
      { title: "De la captation au montage", text: "Une équipe qui gère tournage, photographie, montage et motion design de bout en bout." },
    ],
    deliverables: ["Photographie produit", "Vidéos publicitaires", "Montage vidéo", "Motion design", "Séquences pour réseaux sociaux", "Sous-titrage et formats adaptés"],
    process: [
      { title: "Brief créatif", text: "Objectif, message, support de diffusion et direction artistique souhaitée." },
      { title: "Préparation", text: "Storyboard, lieux, casting et planning du tournage ou de la séance." },
      { title: "Captation", text: "Tournage photo ou vidéo professionnel selon le plan établi." },
      { title: "Post-production", text: "Montage, étalonnage, motion design et livraison aux formats requis." },
    ],
    audiences: ["Marques et commerces", "Campagnes publicitaires", "Réseaux sociaux et influence", "Événements et lancements produits"],
    faq: [
      { q: "Quels formats livrez-vous ?", a: "Vidéos verticales et horizontales, spots, photos haute résolution et déclinaisons pour chaque plateforme, selon l’usage prévu." },
      { q: "Gérez-vous le tournage sur place ?", a: "Oui. Nous assurons le repérage, le matériel, la direction et la captation sur site ou en studio selon votre besoin." },
      { q: "Pouvez-vous créer des vidéos animées ?", a: "Oui. Le motion design permet d’animer des logos, infographies et messages pour les formats web et publicitaires." },
      { q: "Combien de temps pour une vidéo ?", a: "Cela dépend de la complexité, du tournage et de la post-production. Nous établissons un délai clair avant le lancement." },
    ],
  },
  ar: {
    name: "إنتاج الصور والفيديو",
    metaTitle: "إنتاج صور وفيديو في المغرب",
    metaDescription: "خدمات إنتاج الصور والفيديو في المغرب: تصوير ومونتاج وموشن جرافيك لمحتوى بصري احترافي ومؤثر.",
    eyebrow: "الصور والفيديو · الإنتاج البصري",
    title: "إنتاج صور وفيديو احترافي في المغرب",
    highlight: "محتوى بصري يحيي علامتك ويجذب جمهورك.",
    description: "ننتج الصور والفيديو والموشن جرافيك لحملاتك وشبكات التواصل ووسائطك، بتوجه فني متناسق.",
    introTitle: "الفيديو هو اللغة الأكثر تفاعلاً",
    intro: [
      "صورة مؤطرة جيداً أو فيديو مونتاج احترافي يوصل الرسالة أسرع من نص طويل. نحول منتجاتك وخدماتك وقيمك إلى محتوى بصري جاهز للنشر.",
      "من التصوير إلى مرحلة ما بعد الإنتاج، نغطي التصوير الفوتوغرافي والفيديو والمونتاج والموشن جرافيك بخط فني متوافق مع علامتك.",
    ],
    benefits: [
      { title: "محتوى تفاعلي", text: "تصاميم مصممة لجذب الانتباه وتحقيق تفاعلات على قنواتك." },
      { title: "توجه فني", text: "تناسق بصري يحترم هويتك في كل صيغة ننتجها." },
      { title: "من التصوير إلى المونتاج", text: "فريق يدير التصوير والمونتاج والموشن جرافيك من البداية للنهاية." },
    ],
    deliverables: ["تصوير المنتجات", "فيديوهات إعلانية", "مونتاج فيديو", "موشن جرافيك", "مقاطع لشبكات التواصل", "ترجمة وتكييف المقاسات"],
    process: [
      { title: "الموجز الإبداعي", text: "نحدد الهدف والرسالة ووسيلة النشر والتوجه الفني." },
      { title: "التحضير", text: "نص القصة والمواقع وفريق التصوير وجدول التصوير." },
      { title: "التصوير", text: "تصوير احترافي حسب الخطة المتفق عليها." },
      { title: "ما بعد الإنتاج", text: "مونتاج ومعالجة الألوان وموشن جرافيك وتسليم بالصيغ المطلوبة." },
    ],
    audiences: ["العلامات التجارية والمتاجر", "الحملات الإعلانية", "شبكات التواصل والتسويق بالمؤثرين", "الفعاليات وإطلاق المنتجات"],
    faq: [
      { q: "ما الصيغ التي تسلمونها؟", a: "فيديوهات عمودية وأفقية وإعلانات وصور عالية الدقة وتفريعات لكل منصة حسب الاستخدام." },
      { q: "هل تديرون التصوير في الموقع؟", a: "نعم. نغطي تحديد الموقع والتجهيزات والإدارة والتصوير في الموقع أو الاستوديو حسب الحاجة." },
      { q: "هل يمكنكم تصميم فيديوهات متحركة؟", a: "نعم. الموشن جرافيك يسمح بتحريك الشعارات والرسوم والمعلومات للصيغ الرقمية والإعلانية." },
      { q: "كم يستغرق إنتاج فيديو؟", a: "يعتمد على التعقيد والتصوير وما بعد الإنتاج. نحدد مدة واضحة قبل البدء." },
    ],
  },
}
