export const photoVideo = {
  slug: "production-photo-video-maroc",
  icon: "Clapperboard",
  related: ["social-media-maroc", "publicite-payante-maroc", "marketing-influence-maroc"],
  fr: {
    name: "Production photo & vidéo",
    metaTitle: "Production vidéo à Casablanca | Photo & contenu visuel",
    metaTitleAbsolute: true,
    metaDescription: "Production vidéo à Casablanca : cadrage et coordination de contenus photo et vidéo pour les entreprises au Maroc.",
    eyebrow: "Production vidéo · Casablanca & Maroc",
    title: "Production vidéo à Casablanca",
    highlight: "Des contenus photo et vidéo organisés autour d’un périmètre approuvé.",
    description: "Nous accompagnons les entreprises à Casablanca dans le cadrage et la coordination de contenus photo et vidéo pour leurs communications au Maroc.",
    introTitle: "Des contenus visuels préparés pour un usage défini",
    intro: [
      "Un projet de contenu photo ou vidéo commence par un brief, un usage de communication identifié et des références visuelles approuvées. Ces repères permettent de définir un périmètre de production lisible.",
      "Nous coordonnons les contenus prévus, la revue des livrables convenus et leur livraison selon le périmètre validé pour votre projet au Maroc.",
    ],
    benefits: [
      { title: "Périmètre de production clair", text: "Un brief et un usage défini pour organiser les contenus attendus." },
      { title: "Références visuelles approuvées", text: "Des contenus photo et vidéo alignés sur les références et le contexte validés." },
      { title: "Coordination des livrables approuvés", text: "Une coordination des contenus prévus, de leur revue et de leur livraison selon le périmètre convenu." },
    ],
    deliverables: ["Brief de projet et usage prévu", "Périmètre de contenus photo et vidéo", "Références visuelles approuvées", "Coordination de la captation ou création prévue", "Revue des livrables approuvés", "Coordination de la livraison selon le périmètre convenu"],
    process: [
      { title: "Brief & périmètre", text: "Définition de l’usage de communication, des contenus attendus et du périmètre approuvé." },
      { title: "Références & planification des livrables", text: "Validation des références visuelles et organisation des livrables prévus." },
      { title: "Coordination de la production approuvée", text: "Coordination de la captation ou création prévue dans le périmètre validé." },
      { title: "Revue & coordination de la livraison", text: "Revue des livrables convenus et coordination de leur livraison selon le périmètre défini." },
    ],
    audiences: ["Entreprises ayant besoin de contenus vidéo approuvés", "Marques nécessitant des assets photo et vidéo pour leur communication", "Équipes e-commerce ou produit ayant besoin d’une coordination de contenus visuels", "Équipes de campagne ayant besoin d’assets visuels approuvés"],
    faq: [
      { q: "Quels contenus photo et vidéo pouvez-vous accompagner ?", a: "Nous cadrons des contenus photo et vidéo selon le brief, l’usage de communication, le périmètre approuvé et les références visuelles validées pour le projet." },
      { q: "Comment démarre un projet de production photo ou vidéo ?", a: "Le projet commence par le brief, l’usage prévu et les références approuvées. Nous définissons ensuite le périmètre des contenus et coordonnons les livrables convenus." },
      { q: "Les contenus produits peuvent-ils être utilisés pour une campagne publicitaire ?", a: "Des assets photo ou vidéo peuvent être préparés pour l’usage de campagne approuvé. La diffusion payante et la gestion de campagne relèvent du service Publicité payante." },
      { q: "Gérez-vous la diffusion sur les réseaux sociaux ou avec des créateurs ?", a: "La production photo et vidéo relève de ce service. La gestion organique des réseaux sociaux relève du service Réseaux sociaux, et la coordination de campagnes créateurs du service Marketing d’influence." },
    ],
  },
  en: {
    name: "Photo & video production",
    metaTitle: "Video Production Company in Casablanca | Photo & Visual Content",
    metaTitleAbsolute: true,
    metaDescription: "Video production company in Casablanca: scoping and coordination of photo and video content for businesses across Morocco.",
    eyebrow: "Video production · Casablanca & Morocco",
    title: "Video Production Company in Casablanca",
    highlight: "Photo and video content organised around an approved scope.",
    description: "We support businesses in Casablanca with scoping and coordination of photo and video content for communications across Morocco.",
    introTitle: "Visual content prepared for a defined use",
    intro: [
      "A photo or video content project begins with a brief, an identified communication use and approved visual references. These foundations make it possible to define a clear production scope.",
      "We coordinate the planned content, review agreed deliverables and coordinate their delivery according to the approved scope for your project across Morocco.",
    ],
    benefits: [
      { title: "Clear production scope", text: "A brief and defined use to organise the expected content." },
      { title: "Approved visual references", text: "Photo and video content aligned with the approved references and project context." },
      { title: "Coordination of approved deliverables", text: "Coordination of planned content, its review and delivery according to the agreed scope." },
    ],
    deliverables: ["Project brief and intended use", "Photo and video content scope", "Approved visual references", "Coordination of planned capture or creation", "Review of approved deliverables", "Delivery coordination according to the agreed scope"],
    process: [
      { title: "Brief and scope", text: "Defining the communication use, expected content and approved scope." },
      { title: "References and deliverable planning", text: "Approving visual references and organising the planned deliverables." },
      { title: "Coordination of approved production", text: "Coordinating the planned capture or creation within the validated scope." },
      { title: "Review and delivery coordination", text: "Reviewing agreed deliverables and coordinating their delivery according to the defined scope." },
    ],
    audiences: ["Businesses needing approved video content", "Brands needing photo and video assets for communication", "E-commerce or product teams needing visual-content coordination", "Campaign teams needing approved visual assets"],
    faq: [
      { q: "What photo and video content can you support?", a: "We scope photo and video content around the brief, communication use, approved scope and visual references validated for the project." },
      { q: "How does a photo or video production project begin?", a: "The project begins with the brief, intended use and approved references. We then define the content scope and coordinate the agreed deliverables." },
      { q: "Can produced content be used for an advertising campaign?", a: "Photo or video assets can be prepared for approved campaign use. Paid distribution and campaign management belong to the Paid Advertising service." },
      { q: "Do you manage distribution on social media or with creators?", a: "Photo and video production belongs to this service. Organic social media management belongs to the Social Media service, while creator-campaign coordination belongs to Influencer Marketing." },
    ],
  },
}
