export const publicitePayante = {
  slug: "publicite-payante-maroc",
  icon: "Megaphone",
  related: ["marketing-influence-maroc", "email-marketing-maroc", "social-media-maroc", "seo-maroc"],
  fr: {
    name: "Publicité payante",
    metaTitle: "Publicité au Maroc : Meta, Google et TikTok",
    metaDescription: "Publicité payante au Maroc : Meta Ads, Google Ads et TikTok Ads pour générer des leads qualifiés et maximiser votre retour sur investissement.",
    eyebrow: "Publicité · Meta, Google & TikTok",
    title: "Publicité payante Meta Ads, Google Ads et TikTok Ads au Maroc",
    highlight: "Des campagnes publicitaires rentables et ciblées pour générer des leads qualifiés.",
    description: "Nous concevons et gérons vos campagnes publicitaires sur Meta Ads, Google Ads et TikTok Ads pour maximiser votre visibilité et votre retour sur investissement avec des ciblages précis.",
    introTitle: "Chaque dirham investi doit servir un objectif mesurable",
    intro: [
      "La publicité payante fonctionne quand elle est ciblée, mesurée et optimisée en continu. Nous sélectionnons les plateformes adaptées à votre audience et créons des campagnes qui convertissent.",
      "Du paramétrage initial au suivi des performances, nous optimisons vos enchères, vos créatifs et vos audiences pour améliorer le coût par acquisition et le retour sur investissement.",
    ],
    benefits: [
      { title: "Ciblage précis", text: "Segmentation par centres d'intérêt, comportement et localisation pour toucher les bonnes personnes." },
      { title: "Optimisation continue", text: "Ajustements réguliers des enchères, des créatifs et des audiences selon les performances." },
      { title: "ROI mesurable", text: "Suivi des coûts par acquisition, du retour sur investissement et des conversions par plateforme." },
    ],
    deliverables: ["Audit & stratégie publicitaire", "Création de campagnes", "Ciblages avancés", "Créatifs publicitaires", "Suivi et optimisation", "Reporting mensuel"],
    process: [
      { title: "Diagnostic", text: "Analyse de votre marché, objectifs et canaux les plus pertinents pour votre activité." },
      { title: "Stratégie", text: "Choix des plateformes, structure des campagnes, audiences et budget alloué." },
      { title: "Lancement", text: "Création des campagnes, paramétrage du tracking et validation avant diffusion." },
      { title: "Optimisation", text: "Suivi des performances, ajustements et améliorations continues pour maximiser le ROI." },
    ],
    audiences: ["E-commerces et marques", "Campagnes de lancement", "Génération de leads B2B", "Campagnes de notoriété"],
    faq: [
      { q: "Quelle plateforme choisir pour mon activité ?", a: "Cela dépend de votre audience, de votre objectif et de votre budget. Meta Ads est souvent préféré pour le B2C, Google Ads pour l'intention de recherche, TikTok pour les audiences jeunes et créatives." },
      { q: "Quel budget publicitaire prévoir ?", a: "Nous recommandons un minimum suffisant pour obtenir des données exploitables. Après une phase de test, nous ajustons le budget selon le coût par acquisition et le retour observé." },
      { q: "Comment mesurez-vous les résultats ?", a: "Nous utilisons les pixels et outils de suivi pour mesurer les conversions, le coût par lead, le ROAS et les indicateurs clés définis ensemble." },
      { q: "Pouvez-vous gérer des campagnes existantes ?", a: "Oui. Nous auditons les comptes existants et proposons des améliorations structurelles et créatives pour améliorer les performances." },
    ],
  },
  en: {
    name: "Paid advertising",
    metaTitle: "Advertising in Morocco: Meta, Google and TikTok",
    metaDescription: "Paid advertising in Morocco: Meta Ads, Google Ads and TikTok Ads to generate qualified leads and maximise your return on investment.",
    eyebrow: "Advertising · Meta, Google & TikTok",
    title: "Paid advertising with Meta Ads, Google Ads and TikTok Ads in Morocco",
    highlight: "Targeted, profitable advertising campaigns to generate qualified leads.",
    description: "We design and manage your advertising campaigns on Meta Ads, Google Ads and TikTok Ads to maximise your visibility and return on investment through precise targeting.",
    introTitle: "Every dirham invested should serve a measurable objective",
    intro: [
      "Paid advertising works when it is targeted, measured and continuously optimised. We select platforms suited to your audience and create campaigns that convert.",
      "From initial setup to performance monitoring, we optimise your bids, creative assets and audiences to improve cost per acquisition and return on investment.",
    ],
    benefits: [
      { title: "Precise targeting", text: "Segmentation by interests, behaviour and location to reach the right people." },
      { title: "Continuous optimisation", text: "Regular adjustments to bids, creative assets and audiences based on performance." },
      { title: "Measurable ROI", text: "Tracking cost per acquisition, return on investment and conversions by platform." },
    ],
    deliverables: ["Advertising audit & strategy", "Campaign creation", "Advanced targeting", "Ad creative", "Monitoring and optimisation", "Monthly reporting"],
    process: [
      { title: "Assessment", text: "Analysis of your market, objectives and the channels most relevant to your business." },
      { title: "Strategy", text: "Platform selection, campaign structure, audiences and allocated budget." },
      { title: "Launch", text: "Campaign creation, tracking setup and validation before going live." },
      { title: "Optimisation", text: "Performance monitoring, adjustments and continuous improvements to maximise ROI." },
    ],
    audiences: ["E-commerce businesses and brands", "Launch campaigns", "B2B lead generation", "Brand awareness campaigns"],
    faq: [
      { q: "Which platform should I choose for my business?", a: "It depends on your audience, objective and budget. Meta Ads is often preferred for B2C, Google Ads for search intent, and TikTok for younger, creative audiences." },
      { q: "What advertising budget should I plan for?", a: "We recommend a sufficient minimum budget to obtain usable data. After a testing phase, we adjust the budget according to cost per acquisition and the observed return." },
      { q: "How do you measure results?", a: "We use pixels and tracking tools to measure conversions, cost per lead, ROAS and the key metrics we define together." },
      { q: "Can you manage existing campaigns?", a: "Yes. We audit existing accounts and recommend structural and creative improvements to improve performance." },
    ],
  },
}
