export const publicitePayante = {
  slug: "publicite-payante-maroc",
  icon: "Megaphone",
  related: ["marketing-influence-maroc", "social-media-maroc", "seo-maroc"],
  fr: {
    name: "Publicité payante",
    metaTitle: "Publicité payante Meta Ads Google Ads TikTok Ads au Maroc",
    metaDescription: "Publicité payante au Maroc : Meta Ads, Google Ads et TikTok Ads pour générer des leads qualifiés et maximiser votre retour sur investissement.",
    eyebrow: "Publicité · Meta, Google & TikTok",
    title: "Publicité payante Meta Ads, Google Ads et TikTok Ads au Maroc",
    highlight: "Des campagnes publicitaires rentables et ciblées pour générer des leads qualifiés.",
    description: "Nous concevons et gérons vos campagnes publicitaires sur Meta Ads, Google Ads et TikTok Ads pour maximiser votre visibilité et votre retour sur investissement avec des ciblages précis.",
    introTitle: "Chaque dirham investi doit servir un objectif mesurable",
    intro: [
      "La publicité payante fonctionne quand elle est ciblée, mesurée et optimisée en continu. Nous sélectionnons les plateformes adaptées à votre audience et créons des campagnes qui convertissent.",
      "Du paramétrage initial au suivi des performances, nous optimisons vos enchères, vos créatifs et vos audiences pour améliorer le coût par acquisition et le retour sur investissement.",
    ],
    benefits: [
      { title: "Ciblage précis", text: "Segmentation par centres d'intérêt, comportement et localisation pour toucher les bonnes personnes." },
      { title: "Optimisation continue", text: "Ajustements réguliers des enchères, des créatifs et des audiences selon les performances." },
      { title: "ROI mesurable", text: "Suivi des coûts par acquisition, du retour sur investissement et des conversions par plateforme." },
    ],
    deliverables: ["Audit & stratégie publicitaire", "Création de campagnes", "Ciblages avancés", "Créatifs publicitaires", "Suivi et optimisation", "Reporting mensuel"],
    process: [
      { title: "Diagnostic", text: "Analyse de votre marché, objectifs et canaux les plus pertinents pour votre activité." },
      { title: "Stratégie", text: "Choix des plateformes, structure des campagnes, audiences et budget alloué." },
      { title: "Lancement", text: "Création des campagnes, paramétrage du tracking et validation avant diffusion." },
      { title: "Optimisation", text: "Suivi des performances, ajustements et améliorations continues pour maximiser le ROI." },
    ],
    audiences: ["E-commerces et marques", "Campagnes de lancement", "Génération de leads B2B", "Campagnes de notoriété"],
    faq: [
      { q: "Quelle plateforme choisir pour mon activité ?", a: "Cela dépend de votre audience, de votre objectif et de votre budget. Meta Ads est souvent préféré pour le B2C, Google Ads pour l'intention de recherche, TikTok pour les audiences jeunes et créatives." },
      { q: "Quel budget publicitaire prévoir ?", a: "Nous recommandons un minimum suffisant pour obtenir des données exploitables. Après une phase de test, nous ajustons le budget selon le coût par acquisition et le retour observé." },
      { q: "Comment mesurez-vous les résultats ?", a: "Nous utilisons les pixels et outils de suivi pour mesurer les conversions, le coût par lead, le ROAS et les indicateurs clés définis ensemble." },
      { q: "Pouvez-vous gérer des campagnes existantes ?", a: "Oui. Nous auditons les comptes existants et proposons des améliorations structurelles et créatives pour améliorer les performances." },
    ],
  },
  ar: {
    name: "الإعلانات المدفوعة",
    metaTitle: "الإعلانات المدفوعة Meta Ads Google Ads TikTok Ads في المغرب",
    metaDescription: "الإعلانات المدفوعة في المغرب: Meta Ads وGoogle Ads وTikTok Ads لجذب عملاء محتملين مؤهلين وتعظيم العائد على الاستثمار.",
    eyebrow: "إعلانات · Meta وGoogle وTikTok",
    title: "الإعلانات المدفوعة Meta Ads وGoogle Ads وTikTok Ads في المغرب",
    highlight: "حملات إعلانية موجهة وذات عائد لاستثمارك.",
    description: "نصمم وندير حملاتك الإعلانية على Meta Ads وGoogle Ads وTikTok Ads لتعزيز ظهورك وتحقيق عائد استثمار أعلى بتحديد دقيق للجمهور.",
    introTitle: "كل درهم مستثمر يجب أن يخدم هدفاً قابلاً للقياس",
    intro: [
      "الإعلانات المدفوعة تعمل حين تكون موجهة وموضوعة ومحسّنة باستمرار. نختار المنصات المناسبة لجمهورك وننشئ حملات تتحول.",
      "من الإعداد الأولي إلى متابعة الأداء، نحسن عروض الأسعار والمحتوى والجمهور لخفض تكلفة الاستحواذ وتحسين العائد على الاستثمار.",
    ],
    benefits: [
      { title: "تحديد دقيق", text: "تجزئة حسب الاهتمامات والسلوك والموقع للوصول إلى الأشخاص المناسبين." },
      { title: "تحسين مستمر", text: "تعديلات منتظمة للعروض والمحتوى والجمهور حسب الأداء." },
      { title: "عائد قابل للقياس", text: "متابعة تكلفة الاستحواذ والعائد على الاستثمار والتحويلات لكل منصة." },
    ],
    deliverables: ["تدقيق واستراتيجية إعلانية", "إنشاء الحملات", "تحديد دقيق للجمهور", "تصاميم إعلانية", "المتابعة والتحسين", "تقارير شهرية"],
    process: [
      { title: "التشخيص", text: "تحليل السوق وأهدافك والقنوات الأكثر ملاءمة لنشاطك." },
      { title: "الاستراتيجية", text: "اختيار المنصات وهيكل الحملات والجمهور والميزانية المخصصة." },
      { title: "الإطلاق", text: "إنشاء الحملات وإعداد التتبع والتحقق قبل النشر." },
      { title: "التحسين", text: "متابعة الأداء والتعديلات المستمرة لتعظيم العائد على الاستثمار." },
    ],
    audiences: ["متاجر إلكترونية وعلامات", "حملات الإطلاق", "توليد عملاء محتملين B2B", "حملات الظهور"],
    faq: [
      { q: "ما المنصة الأنسب لنشاطي؟", a: "يعتمد على جمهورك وهدفك وميزانيتك. Meta Ads مفضل غالباً لـB2C، وGoogle Ads للبحث الوارد، وTikTok للجمهور الشاب والإبداعي." },
      { q: "ما ميزانية الإعلانات المطلوبة؟", a: "نوصي بمبلغ كافٍ للحصول على بيانات قابلة للاستخدام. بعد مرحلة الاختبار، نعدل الميزانية حسب تكلفة الاستحواذ والعائد." },
      { q: "كيف تقيسون النتائج؟", a: "نستخدم البيكسل وأدوات التتبع لقياس التحويلات وتكلفة العميل المحتمل والعائد على الإنفاق والمؤشرات المتفق عليها." },
      { q: "هل يمكنكم إدارة حملات موجودة؟", a: "نعم. نتدقق في الحسابات الموجودة ونقترح تحسينات هيكلية وإبداعية لرفع الأداء." },
    ],
  },
}
