export const publicitePayante = {
  slug: "publicite-payante-maroc",
  icon: "Megaphone",
  related: ["landing-page-maroc", "design-graphique-maroc", "seo-maroc"],
  fr: {
    name: "Publicité payante",
    metaTitle: "Agence de publicité en ligne à Casablanca | Google & Meta Ads",
    metaTitleAbsolute: true,
    metaDescription: "Agence de publicité en ligne à Casablanca : gestion de campagnes Google Ads, Meta Ads et TikTok Ads, suivi des données et reporting pour les entreprises au Maroc.",
    eyebrow: "Publicité en ligne · Casablanca & Maroc",
    title: "Agence de publicité en ligne à Casablanca",
    highlight: "Des campagnes cadrées, suivies et ajustées autour d’un objectif défini.",
    description: "Nous gérons des campagnes Google Ads, Meta Ads et TikTok Ads pour les entreprises de Casablanca et du Maroc, avec une structure claire, un ciblage adapté et un suivi des données disponibles.",
    introTitle: "Piloter les campagnes payantes avec un cadre clair",
    intro: [
      "Une campagne payante commence par un objectif, une audience et une destination clairement définis. Nous choisissons les plateformes adaptées, organisons les campagnes et préparons le ciblage ainsi que les messages à diffuser.",
      "Du lancement au reporting, nous suivons les dépenses et les données observées dans les comptes configurés. Les ajustements portent sur la structure, le ciblage, le budget et les messages selon les signaux disponibles.",
    ],
    benefits: [
      { title: "Campagnes structurées", text: "Un cadrage de l’objectif, des plateformes, des audiences et des messages avant la mise en ligne." },
      { title: "Suivi du budget et des campagnes", text: "Lecture régulière des dépenses, du ciblage et des campagnes actives pour orienter les ajustements." },
      { title: "Reporting basé sur les données observées", text: "Des indicateurs disponibles par plateforme pour suivre l’activité de campagne et éclairer les décisions." },
    ],
    deliverables: ["Audit et cadrage de campagne", "Structure et paramétrage des campagnes", "Ciblage des audiences", "Allocation et suivi du budget", "Messages et coordination des assets fournis", "Mesure, reporting et ajustements"],
    process: [
      { title: "Audit et objectif de campagne", text: "Nous clarifions l’offre, l’audience, la destination et l’action à suivre avant de choisir les plateformes." },
      { title: "Stratégie et structure", text: "Nous organisons les campagnes, le ciblage, les messages et la répartition du budget autour de l’objectif retenu." },
      { title: "Lancement et mesure disponible", text: "Les campagnes sont préparées, validées puis mises en ligne avec les éléments de mesure disponibles dans les comptes configurés." },
      { title: "Suivi, reporting et ajustements", text: "Nous examinons les données observées, partageons le reporting et ajustons les campagnes lorsque les signaux disponibles le justifient." },
    ],
    audiences: ["Entreprises qui activent l’acquisition payante", "Campagnes e-commerce", "Lancements de produits ou services", "Contextes B2B et campagnes de notoriété"],
    faq: [
      { q: "Quelles plateformes publicitaires gérez-vous ?", a: "Nous gérons des campagnes Google Ads, Meta Ads et TikTok Ads selon l’objectif, l’audience et les assets ou données disponibles pour la campagne." },
      { q: "Comment définissez-vous le budget publicitaire ?", a: "Le budget média est distinct de la prestation. Il se définit selon l’objectif de campagne, les plateformes retenues et les données disponibles, puis il est suivi au fil de la diffusion." },
      { q: "Comment mesurez-vous une campagne publicitaire ?", a: "Nous lisons les dépenses, impressions, clics, conversions et coûts observés dans les comptes configurés, selon les éléments de mesure disponibles. Le reporting aide à comprendre l’activité de la campagne sans garantir un résultat." },
      { q: "Créez-vous aussi les landing pages et les visuels ?", a: "Nous coordonnons les besoins de la campagne. La création de landing pages relève du service Landing Pages, les assets graphiques statiques du service Design graphique et la production photo ou vidéo du service Production photo & vidéo." },
    ],
  },
  en: {
    name: "Paid advertising",
    metaTitle: "Paid Advertising Agency in Casablanca | Google & Meta Ads",
    metaTitleAbsolute: true,
    metaDescription: "Paid advertising agency in Casablanca: Google Ads, Meta Ads and TikTok Ads campaign management, measurement and reporting for businesses across Morocco.",
    eyebrow: "Paid advertising · Casablanca & Morocco",
    title: "Paid Advertising Agency in Casablanca",
    highlight: "Campaigns scoped, monitored and adjusted around a defined objective.",
    description: "We manage Google Ads, Meta Ads and TikTok Ads campaigns for businesses in Casablanca and across Morocco, with clear campaign structure, relevant targeting and monitoring of available data.",
    introTitle: "Managing paid campaigns with a clear framework",
    intro: [
      "A paid campaign starts with a clearly defined objective, audience and destination. We select suitable platforms, organise campaigns and prepare the targeting and messaging to be delivered.",
      "From launch to reporting, we monitor spend and observed data in configured accounts. Adjustments can address structure, targeting, budget and messaging according to the signals available.",
    ],
    benefits: [
      { title: "Structured campaign planning", text: "A framework for the objective, platforms, audiences and messaging before campaigns go live." },
      { title: "Budget and campaign monitoring", text: "Regular review of spend, targeting and active campaigns to guide adjustments." },
      { title: "Clear reporting from observed data", text: "Available platform indicators to monitor campaign activity and inform decisions." },
    ],
    deliverables: ["Campaign audit and scoping", "Campaign structure and setup", "Audience targeting", "Budget allocation and monitoring", "Messaging and coordination of supplied assets", "Measurement, reporting and adjustments"],
    process: [
      { title: "Campaign audit and objective", text: "We clarify the offer, audience, destination and action to monitor before selecting platforms." },
      { title: "Strategy and structure", text: "We organise campaigns, targeting, messaging and budget allocation around the chosen objective." },
      { title: "Launch and available measurement", text: "Campaigns are prepared, approved and launched with the measurement elements available in configured accounts." },
      { title: "Monitoring, reporting and adjustments", text: "We review observed data, share reporting and adjust campaigns when the available signals support a change." },
    ],
    audiences: ["Businesses activating paid acquisition", "E-commerce campaigns", "Product or service launches", "B2B contexts and brand-awareness campaigns"],
    faq: [
      { q: "Which advertising platforms do you manage?", a: "We manage Google Ads, Meta Ads and TikTok Ads campaigns according to the objective, audience and assets or data available for the campaign." },
      { q: "How do you define the advertising budget?", a: "Media budget is separate from the service. It is defined around the campaign objective, selected platforms and available data, then monitored as the campaign runs." },
      { q: "How do you measure an advertising campaign?", a: "We review observed spend, impressions, clicks, conversions and costs in configured accounts, according to the measurement available. Reporting helps explain campaign activity without guaranteeing an outcome." },
      { q: "Do you also create landing pages and visual assets?", a: "We coordinate campaign requirements. Landing page creation belongs to the Landing Pages service, static graphic assets to Graphic Design, and photo or video production to Photo & Video Production." },
    ],
  },
}
