export const socialMedia = {
  slug: "social-media-maroc",
  icon: "Share2",
  related: ["design-graphique-maroc", "production-photo-video-maroc", "marketing-influence-maroc"],
  fr: {
    name: "Réseaux sociaux",
    metaTitle: "Gestion des réseaux sociaux au Maroc",
    metaDescription: "Gestion des réseaux sociaux au Maroc : community management, content creation et stratégie sociale pour développer votre présence en ligne et engager votre audience.",
    eyebrow: "Réseaux sociaux · Gestion & contenu",
    title: "Gestion des réseaux sociaux et création de contenu au Maroc",
    highlight: "Une présence sociale cohérente qui construit une communauté fidèle.",
    description: "Nous gérons vos réseaux sociaux, créons du contenu engageant et animons votre communauté pour développer votre visibilité et générer des interactions de qualité.",
    introTitle: "Construire une communauté autour de votre marque",
    intro: [
      "Une présence sociale régulière et cohérente crée une relation de confiance avec votre audience. Nous planifions, créons et animons vos canaux avec un contenu adapté à chaque plateforme.",
      "De la stratégie éditoriale au community management, nous veillons à ce que chaque publication serve votre image de marque et vos objectifs commerciaux.",
    ],
    benefits: [
      { title: "Présence régulière", text: "Un calendrier éditorial structuré pour maintenir une visibilité constante." },
      { title: "Contenu ciblé", text: "Publications adaptées à chaque réseau pour maximiser l’engagement auprès de votre audience." },
      { title: "Communauté active", text: "Des interactions authentiques avec votre public pour renforcer la fidélité et la confiance." },
    ],
    deliverables: ["Stratégie éditoriale", "Création de contenu", "Community management", "Calendrier de publication", "Reportings mensuels", "Modération et engagement"],
    process: [
      { title: "Audit & objectifs", text: "Analyse de votre présence actuelle, benchmarks et définition des objectifs par canal." },
      { title: "Stratégie", text: "Tons, formats, fréquence et ligne éditoriale alignée sur votre marque." },
      { title: "Création & planification", text: "Production des visuels et textes, planification et programmation des publications." },
      { title: "Animation & pilotage", text: "Community management, suivi des performances et ajustements continus. Reporting mensuel." },
    ],
    audiences: ["Marques locales et nationales", "E-commerces et boutiques", "Restaurants, hôtels et services", "Créateurs et influenceurs"],
    faq: [
      { q: "Quels réseaux sociaux gérez-vous ?", a: "Nous travaillons principalement avec Instagram, Facebook, LinkedIn, TikTok et YouTube. Le choix dépend de votre secteur et de votre audience cible." },
      { q: "Fournissez-vous les visuels ?", a: "Oui. La création de contenu visuel est incluse dans notre accompagnement : photos, vidéos courtes, stories et carrousels." },
      { q: "Comment mesurez-vous les résultats ?", a: "Nous suivons les indicateurs clés (portée, engagement, trafic, conversions) et fournissons un reporting mensuel." },
      { q: "Pouvez-vous gérer des comptes existants ?", a: "Oui. Nous reprenons la gestion après un audit, en respectant l’historique et la communauté déjà construite." },
    ],
  },
  ar: {
    name: "إدارة وسائل التواصل",
    metaTitle: "إدارة وسائل التواصل الاجتماعي في المغرب",
    metaDescription: "إدارة وسائل التواصل الاجتماعي في المغرب: إدارة المجتمعات وإنشاء المحتوى واستراتيجية رقمية لتعزيز حضورك والتفاعل مع جمهورك.",
    eyebrow: "شبكات التواصل · الإدارة والمحتوى",
    title: "إدارة شبكات التواصل الاجتماعي وإنشاء المحتوى في المغرب",
    highlight: "وجود اجتماعي متناسق يبني مجتمعاً وفياً.",
    description: "ندير شبكات التواصل الاجتماعي، ننتج محتوى تفاعلياً وندير مجتمعك لتعزيز ظهورك وتحقيق تفاعلات نوعية.",
    introTitle: "ابنِ مجتمعاً حول علامتك",
    intro: [
      "الوجود الاجتماعي المنتظم والمتناسق يبني ثقة مع جمهورك. نخطط وننتج وندير قنواتك بمحتوى مناسب لكل منصة.",
      "من الاستراتيجية التحريرية إلى إدارة المجتمع، نحرص على أن كل منشور يخدم هويتك وأهدافك التجارية.",
    ],
    benefits: [
      { title: "حضور منتظم", text: "جدول تحريري منظم يحافظ على ظهور ثابت." },
      { title: "محتوى موجه", text: "منشورات مكيفة لكل شبكة لتحقيق تفاعل أعلى من جمهورك." },
      { title: "مجتمع نشط", text: "تفاعلات حقيقية تعزز الولاء والثقة مع جمهورك." },
    ],
    deliverables: ["استراتيجية تحريرية", "إنشاء محتوى", "إدارة المجتمع", "جدول النشر", "تقارير شهرية", "إشراف وتفاعل"],
    process: [
      { title: "تدقيق وأهداف", text: "نحلل حضورك الحالي والمنافسين ونحدد الأهداف لكل قناة." },
      { title: "الاستراتيجية", text: "النبرة والأشكال والتكرار والخط التحريري المتوافق مع علامتك." },
      { title: "الإنتاج والجدولة", text: "إنشاء النصوص والتصاميم وتنظيم وجدولة المنشورات." },
      { title: "التحريك والقياس", text: "إدارة المجتمع ومتابعة الأداء وتعديلات مستمرة وتقرير شهري." },
    ],
    audiences: ["علامات محلية ووطنية", "متاجر إلكترونية", "مطاعم وفنادق وخدمات", "مبدعون ومؤثرون"],
    faq: [
      { q: "ما شبكات التواصل التي تديرونها؟", a: "نعمل أساساً مع إنستغرام وفيسبوك ولينكدإن وتيك توك ويوتيوب. الاختيار يعتمد على قطاعك وجمهورك المستهدف." },
      { q: "هل تقدمون التصاميم أيضاً؟", a: "نعم. إنشاء المحتوى البصري مشمول: صور وفيديوهات قصيرة وستوريات وكاروسيلات." },
      { q: "كيف تقيسون النتائج؟", a: "نتابع المؤشرات الأساسية (الوصول والتفاعل والزيارات والتحويلات) ونقدم تقريراً شهرياً." },
      { q: "هل يمكنكم إدارة حسابات موجودة؟", a: "نعم. نستلم الإدارة بعد تدقيق ونحترم التاريخ والمجتمع الموجود." },
    ],
  },
}
