export const socialMedia = {
  slug: "social-media-maroc",
  icon: "Share2",
  related: ["design-graphique-maroc", "production-photo-video-maroc", "marketing-influence-maroc"],
  fr: {
    name: "Réseaux sociaux",
    metaTitle: "Gestion des réseaux sociaux au Maroc",
    metaDescription: "Gestion des réseaux sociaux au Maroc : stratégie, création de contenu et community management pour développer une audience engagée.",
    eyebrow: "Réseaux sociaux · Gestion & contenu",
    title: "Gestion des réseaux sociaux et création de contenu au Maroc",
    highlight: "Une présence sociale cohérente qui construit une communauté fidèle.",
    description: "Nous gérons vos réseaux sociaux, créons du contenu engageant et animons votre communauté pour développer votre visibilité et générer des interactions de qualité.",
    introTitle: "Construire une communauté autour de votre marque",
    intro: [
      "Une présence sociale régulière et cohérente crée une relation de confiance avec votre audience. Nous planifions, créons et animons vos canaux avec un contenu adapté à chaque plateforme.",
      "De la stratégie éditoriale au community management, nous veillons à ce que chaque publication serve votre image de marque et vos objectifs commerciaux.",
    ],
    benefits: [
      { title: "Présence régulière", text: "Un calendrier éditorial structuré pour maintenir une visibilité constante." },
      { title: "Contenu ciblé", text: "Publications adaptées à chaque réseau pour maximiser l’engagement auprès de votre audience." },
      { title: "Communauté active", text: "Des interactions authentiques avec votre public pour renforcer la fidélité et la confiance." },
    ],
    deliverables: ["Stratégie éditoriale", "Création de contenu", "Community management", "Calendrier de publication", "Reportings mensuels", "Modération et engagement"],
    process: [
      { title: "Audit & objectifs", text: "Analyse de votre présence actuelle, benchmarks et définition des objectifs par canal." },
      { title: "Stratégie", text: "Tons, formats, fréquence et ligne éditoriale alignée sur votre marque." },
      { title: "Création & planification", text: "Production des visuels et textes, planification et programmation des publications." },
      { title: "Animation & pilotage", text: "Community management, suivi des performances et ajustements continus. Reporting mensuel." },
    ],
    audiences: ["Marques locales et nationales", "E-commerces et boutiques", "Restaurants, hôtels et services", "Créateurs et influenceurs"],
    faq: [
      { q: "Quels réseaux sociaux gérez-vous ?", a: "Nous travaillons principalement avec Instagram, Facebook, LinkedIn, TikTok et YouTube. Le choix dépend de votre secteur et de votre audience cible." },
      { q: "Fournissez-vous les visuels ?", a: "Oui. La création de contenu visuel est incluse dans notre accompagnement : photos, vidéos courtes, stories et carrousels." },
      { q: "Comment mesurez-vous les résultats ?", a: "Nous suivons les indicateurs clés (portée, engagement, trafic, conversions) et fournissons un reporting mensuel." },
      { q: "Pouvez-vous gérer des comptes existants ?", a: "Oui. Nous reprenons la gestion après un audit, en respectant l’historique et la communauté déjà construite." },
    ],
  },
  en: {
    name: "Social media",
    metaTitle: "Social media management in Morocco",
    metaDescription: "Social media management in Morocco: strategy, content creation and community management to grow an engaged audience.",
    eyebrow: "Social media · Management & content",
    title: "Social media management and content creation in Morocco",
    highlight: "A consistent social presence that builds a loyal community.",
    description: "We manage your social media, create engaging content and foster your community to grow your visibility and generate meaningful interactions.",
    introTitle: "Build a community around your brand",
    intro: [
      "A regular, consistent social presence builds a relationship of trust with your audience. We plan, create and manage your channels with content tailored to each platform.",
      "From editorial strategy to community management, we ensure every post supports your brand image and business goals.",
    ],
    benefits: [
      { title: "Regular presence", text: "A structured editorial calendar to maintain consistent visibility." },
      { title: "Targeted content", text: "Posts tailored to each network to maximise engagement with your audience." },
      { title: "Active community", text: "Authentic interactions with your audience to strengthen loyalty and trust." },
    ],
    deliverables: ["Editorial strategy", "Content creation", "Community management", "Publishing calendar", "Monthly reporting", "Moderation and engagement"],
    process: [
      { title: "Audit & objectives", text: "Analysis of your current presence, benchmarks and definition of objectives by channel." },
      { title: "Strategy", text: "Tone of voice, formats, frequency and editorial direction aligned with your brand." },
      { title: "Creation & planning", text: "Production of visuals and copy, planning and scheduling of publications." },
      { title: "Community management & optimisation", text: "Community management, performance monitoring and ongoing adjustments. Monthly reporting." },
    ],
    audiences: ["Local and national brands", "E-commerce businesses and shops", "Restaurants, hotels and services", "Creators and influencers"],
    faq: [
      { q: "Which social media platforms do you manage?", a: "We primarily work with Instagram, Facebook, LinkedIn, TikTok and YouTube. The choice depends on your sector and target audience." },
      { q: "Do you provide the visuals?", a: "Yes. Visual content creation is included in our support: photos, short videos, stories and carousels." },
      { q: "How do you measure results?", a: "We track key metrics (reach, engagement, traffic and conversions) and provide monthly reporting." },
      { q: "Can you manage existing accounts?", a: "Yes. We take over management after an audit, respecting the history and community already built." },
    ],
  },
}
