export const socialMedia = {
  slug: "social-media-maroc",
  icon: "Share2",
  related: ["design-graphique-maroc", "publicite-payante-maroc", "production-photo-video-maroc"],
  fr: {
    name: "Réseaux sociaux",
    metaTitle: "Gestion des réseaux sociaux à Casablanca | Community management",
    metaTitleAbsolute: true,
    metaDescription: "Gestion des réseaux sociaux à Casablanca : stratégie éditoriale, calendrier, publication, community management et reporting pour les entreprises au Maroc.",
    eyebrow: "Gestion des réseaux sociaux · Casablanca & Maroc",
    title: "Gestion des réseaux sociaux à Casablanca",
    highlight: "Une gestion structurée de vos canaux sociaux au fil des publications.",
    description: "Nous assurons à Casablanca la gestion organique de vos réseaux sociaux pour les entreprises au Maroc : stratégie éditoriale, planification, publication, community management et reporting.",
    introTitle: "Une gestion continue de vos canaux sociaux",
    intro: [
      "Nous organisons la gestion organique de vos canaux sociaux : ligne éditoriale, calendrier, préparation des publications, programmation et suivi de votre communauté.",
      "Les contenus et assets validés sont adaptés au calendrier et aux plateformes retenues. La gestion couvre la publication, la modération et un reporting régulier des indicateurs convenus.",
    ],
    benefits: [
      { title: "Planification éditoriale", text: "Une ligne éditoriale et un calendrier structurés pour organiser les publications." },
      { title: "Gestion des canaux", text: "Publication régulière, community management et modération selon le périmètre défini." },
      { title: "Reporting clair", text: "Un suivi régulier des indicateurs convenus pour documenter l’activité des canaux." },
    ],
    deliverables: ["Stratégie réseaux sociaux", "Planification & calendrier éditorial", "Publication & programmation", "Community management", "Modération & gestion des interactions", "Reporting & suivi des performances"],
    process: [
      { title: "Audit & cadrage", text: "Analyse de la présence existante, des canaux concernés et du périmètre de gestion." },
      { title: "Planification éditoriale", text: "Définition de la ligne éditoriale, des formats et du calendrier de publication." },
      { title: "Publication & community management", text: "Programmation des contenus validés, modération et gestion des interactions selon le périmètre." },
      { title: "Reporting & suivi", text: "Partage régulier des indicateurs convenus et ajustements factuels de la planification." },
    ],
    audiences: ["Entreprises ayant besoin de publications régulières", "Marques nécessitant une planification éditoriale", "Équipes ayant besoin de community management et de modération", "Entreprises souhaitant un reporting social structuré"],
    faq: [
      { q: "Que comprend la gestion des réseaux sociaux ?", a: "L’accompagnement peut couvrir la stratégie éditoriale, la planification, la publication, le community management, la modération et le reporting selon le périmètre défini." },
      { q: "Sur quels réseaux sociaux intervenez-vous ?", a: "Nous intervenons principalement sur Instagram, Facebook, LinkedIn, TikTok et YouTube. Le choix des canaux dépend de votre secteur, de votre audience et du périmètre convenu." },
      { q: "Fournissez-vous un calendrier éditorial ?", a: "Oui. Un calendrier éditorial organise les thèmes, formats et dates de publication afin de préparer et valider les contenus avant leur programmation." },
      { q: "Comment fonctionne le reporting ?", a: "Nous partageons un reporting régulier avec les indicateurs convenus pour suivre l’activité des canaux et documenter les ajustements de planification." },
    ],
    resources: [
      { id: "marketing-reseaux-sociaux-maroc", title: "Réseaux sociaux au Maroc : stratégies qui marchent en 2026", description: "Un guide sur les plateformes, les piliers éditoriaux et les repères de stratégie sociale au Maroc." },
    ],
  },
  en: {
    name: "Social media",
    metaTitle: "Social Media Management in Casablanca | Community Management",
    metaTitleAbsolute: true,
    metaDescription: "Social media management in Casablanca: editorial strategy, planning, publishing, community management and reporting for businesses across Morocco.",
    eyebrow: "Social media management · Casablanca & Morocco",
    title: "Social Media Management in Casablanca",
    highlight: "Structured management of your social channels across each publication.",
    description: "We provide organic social media management in Casablanca for businesses across Morocco: editorial strategy, planning, publishing, community management and reporting.",
    introTitle: "Ongoing management for your social channels",
    intro: [
      "We organise the organic management of your social channels: editorial direction, calendar, publication preparation, scheduling and community monitoring.",
      "Approved content and assets are adapted to the agreed calendar and platforms. Management covers publishing, moderation and regular reporting on the agreed indicators.",
    ],
    benefits: [
      { title: "Editorial planning", text: "An editorial direction and structured calendar to organise publications." },
      { title: "Channel management", text: "Regular publishing, community management and moderation within the agreed scope." },
      { title: "Clear reporting", text: "Regular monitoring of agreed indicators to document channel activity." },
    ],
    deliverables: ["Social media strategy", "Editorial planning & calendar", "Publishing & scheduling", "Community management", "Moderation & interaction management", "Reporting & performance monitoring"],
    process: [
      { title: "Audit & scoping", text: "Reviewing the existing presence, relevant channels and management scope." },
      { title: "Editorial planning", text: "Defining editorial direction, formats and the publishing calendar." },
      { title: "Publishing & community management", text: "Scheduling approved content, moderation and interaction management within the agreed scope." },
      { title: "Reporting & monitoring", text: "Sharing agreed indicators regularly and making factual planning adjustments." },
    ],
    audiences: ["Businesses needing regular social publishing", "Brands requiring editorial planning", "Teams needing community management and moderation", "Businesses seeking structured social reporting"],
    faq: [
      { q: "What does social media management include?", a: "Support can include editorial strategy, planning, publishing, community management, moderation and reporting according to the agreed scope." },
      { q: "Which social media platforms do you manage?", a: "We primarily work with Instagram, Facebook, LinkedIn, TikTok and YouTube. Channel selection depends on your sector, audience and agreed scope." },
      { q: "Do you provide an editorial calendar?", a: "Yes. An editorial calendar organises themes, formats and publishing dates so content can be prepared and approved before scheduling." },
      { q: "How does reporting work?", a: "We share regular reporting using agreed indicators to track channel activity and document planning adjustments." },
    ],
    resources: [
      { id: "marketing-reseaux-sociaux-maroc", title: "Social media in Morocco: strategies that work in 2026", description: "A guide to platforms, editorial pillars and social-media strategy references in Morocco." },
    ],
  },
}
